
export const exerciseData = {
  aula1: [
    { q: "Yesterday I ___ very tired.", k: "was" },
    { q: "They ___ at the park last weekend.", k: "were" },
    { q: "She ___ happy to see him.", k: "was" },
    { q: "We ___ not at home yesterday evening.", k: "were" },
    { q: "He ___ a student last year.", k: "was" },
    { q: "You ___ late for the meeting.", k: "were" },
    { q: "It ___ a sunny day.", k: "was" },
    { q: "My parents ___ on vacation.", k: "were" },
    { q: "I ___ sick yesterday.", k: "was" },
    { q: "The kids ___ noisy.", k: "were" },
    { q: "She ___ a doctor.", k: "was" },
    { q: "We ___ friends in high school.", k: "were" },
    { q: "He ___ in London last month.", k: "was" },
    { q: "You ___ right.", k: "were" },
    { q: "It ___ cold this morning.", k: "was" },
    { q: "They ___ busy.", k: "were" },
    { q: "I ___ at the office.", k: "was" },
    { q: "She ___ beautiful.", k: "was" },
    { q: "We ___ hungry.", k: "were" },
    { q: "He ___ smart.", k: "was" },
    { q: "You ___ a good student.", k: "were" },
    { q: "It ___ interesting.", k: "was" },
    { q: "They ___ sad.", k: "were" },
    { q: "I ___ excited.", k: "was" },
    { q: "She ___ tall.", k: "was" },
    { q: "We ___ together.", k: "were" },
    { q: "He ___ kind.", k: "was" },
    { q: "You ___ lucky.", k: "were" },
    { q: "It ___ easy.", k: "was" },
    { q: "They ___ tired.", k: "were" },
    { q: "I ___ happy.", k: "was" },
    { q: "She ___ brave.", k: "was" },
    { q: "We ___ confused.", k: "were" },
    { q: "He ___ strong.", k: "was" },
    { q: "You ___ amazing.", k: "were" },
    { q: "It ___ difficult.", k: "was" },
    { q: "They ___ surprised.", k: "were" },
    { q: "I ___ curious.", k: "was" },
    { q: "She ___ quiet.", k: "was" },
    { q: "We ___ prepared.", k: "were" },
    { q: "He ___ calm.", k: "was" },
    { q: "You ___ thoughtful.", k: "were" },
    { q: "It ___ challenging.", k: "was" },
    { q: "They ___ early.", k: "were" },
    { q: "I ___ late.", k: "was" },
    { q: "She ___ patient.", k: "was" },
    { q: "We ___ determined.", k: "were" },
    { q: "He ___ focused.", k: "was" },
    { q: "You ___ inspired.", k: "were" },
    { q: "It ___ quick.", k: "was" },
  ],
  aula2: [
    { q: "My car is ___ than yours. (fast)", k: "faster" },
    { q: "She is ___ than her brother. (tall)", k: "taller" },
    { q: "This book is ___ than that one. (interesting)", k: "more interesting" },
    { q: "He is ___ at math than me. (good)", k: "better" },
    { q: "The weather today is ___ than yesterday. (cold)", k: "colder" },
    { q: "Learning English is ___ than learning Chinese. (easy)", k: "easier" },
    { q: "This sofa is ___ than the chair. (comfortable)", k: "more comfortable" },
    { q: "He runs ___ than his friend. (quickly)", k: "more quickly" },
    { q: "Her house is ___ than mine. (big)", k: "bigger" },
    { q: "The new movie is ___ than the old one. (exciting)", k: "more exciting" },
    { q: "My phone is ___ than yours. (expensive)", k: "more expensive" },
    { q: "She sings ___ than anyone else. (beautifully)", k: "more beautifully" },
    { q: "This exercise is ___ than the last one. (difficult)", k: "more difficult" },
    { q: "He works ___ than his colleagues. (hard)", k: "harder" },
    { q: "The blue dress is ___ than the red one. (pretty)", k: "prettier" },
    { q: "The city is ___ than the countryside. (noisy)", k: "noisier" },
    { q: "His ideas are ___ than hers. (creative)", k: "more creative" },
    { q: "The journey was ___ than we expected. (long)", k: "longer" },
    { q: "She is ___ in her studies. (diligent)", k: "more diligent" },
    { q: "This restaurant is ___ than that one. (popular)", k: "more popular" },
    { q: "The test was ___ than I thought. (easy)", k: "easier" },
    { q: "He drives ___ than his wife. (carefully)", k: "more carefully" },
    { q: "The new system is ___ than the old one. (efficient)", k: "more efficient" },
    { q: "My new job is ___ than my previous one. (stressful)", k: "more stressful" },
    { q: "She arrived ___ than him. (early)", k: "earlier" },
    { q: "This painting is ___ than the other. (colorful)", k: "more colorful" },
    { q: "He is ___ at playing guitar. (bad)", k: "worse" },
    { q: "The summer is ___ than the winter. (hot)", k: "hotter" },
    { q: "His car is ___ than mine. (old)", k: "older" },
    { q: "This task is ___ than the previous one. (important)", k: "more important" },
    { q: "She speaks English ___ than her sister. (fluently)", k: "more fluently" },
    { q: "The new phone is ___ than the old model. (sleek)", k: "sleeker" },
    { q: "He seems ___ than before. (happy)", k: "happier" },
    { q: "The food here is ___ than at that place. (good)", k: "better" },
    { q: "The problem became ___ over time. (complicated)", k: "more complicated" },
    { q: "Our team played ___ today. (well)", k: "better" },
    { q: "The concert was ___ than the movie. (loud)", k: "louder" },
    { q: "Her explanation was ___ than his. (clear)", k: "clearer" },
    { q: "This project is ___ than the last one. (challenging)", k: "more challenging" },
    { q: "The garden is ___ now. (beautiful)", k: "more beautiful" },
    { q: "He works ___ hours than I do. (long)", k: "longer" },
    { q: "She writes ___ than anyone else. (creatively)", k: "more creatively" },
    { q: "The test was ___ than I expected. (hard)", k: "harder" },
    { q: "This coffee is ___ than the one from Starbucks. (good)", k: "better" },
    { q: "His house is ___ than mine. (far)", k: "farther" },
    { q: "The lecture was ___ than the book. (informative)", k: "more informative" },
    { q: "She is ___ with her hands. (skillful)", k: "more skillful" },
    { q: "The weather is getting ___ every day. (warm)", k: "warmer" },
    { q: "His argument was ___ than hers. (convincing)", k: "more convincing" },
    { q: "The movie was ___ than the book. (boring)", k: "more boring" },
  ],
  aula3: [
    { q: "It's very ___ today, wear a jacket!", k: "cold" },
    { q: "The sun is shining, it's a ___ day.", k: "sunny" },
    { q: "Don't forget your umbrella, it's ___ outside.", k: "rainy" },
    { q: "The trees are moving a lot, it's ___.", k: "windy" },
    { q: "It might ___ tonight, so be careful on the roads.", k: "snowy" },
    { q: "It's so ___ that I can't see the sky.", k: "cloudy" },
    { q: "I love summer, it's always ___ and bright.", k: "hot" },
    { q: "The forecast says it will be ___ tomorrow.", k: "stormy" },
    { q: "After the rain, it became very ___.", k: "humid" },
    { q: "It's a beautiful ___ autumn day.", k: "mild" },
    { q: "The ___ in the desert is extreme.", k: "dry" },
    { q: "It's ___ outside, I need a sweater.", k: "chilly" },
    { q: "The sky is ___ and clear.", k: "clear" },
    { q: "We had a ___ shower this morning.", k: "light rain|lightrain" },
    { q: "There's a strong ___ blowing.", k: "wind" },
    { q: "The mountains are covered in ___.", k: "snow" },
    { q: "It's freezing ___ today.", k: "cold" },
    { q: "I prefer ___ days for a walk.", k: "sunny" },
    { q: "The ___ season is long here.", k: "rainy" },
    { q: "The ___ makes it hard to ride a bike.", k: "wind" },
    { q: "Children love to play in the ___.", k: "snow" },
    { q: "The ___ covered the whole city.", k: "clouds" },
    { q: "We are having a very ___ summer.", k: "hot" },
    { q: "The ___ brought down many trees.", k: "storm" },
    { q: "It's hard to breathe in ___ weather.", k: "humid" },
    { q: "The ___ weather is perfect for hiking.", k: "mild" },
    { q: "Plants don't grow well in ___ climates.", k: "dry" },
    { q: "I feel ___ even indoors.", k: "chilly" },
    { q: "The ___ night was full of stars.", k: "clear" },
    { q: "We need to be prepared for heavy ___.", k: "rain" },
    { q: "The ___ picked up in the afternoon.", k: "wind" },
    { q: "Is it going to ___ tomorrow?", k: "snow" },
    { q: "I don't like ___ days, they are too depressing.", k: "cloudy" },
    { q: "He likes to swim in ___ water.", k: "hot" },
    { q: "A sudden ___ surprised everyone.", k: "storm" },
    { q: "The air is thick and ___.", k: "humid" },
    { q: "We had a ___ winter this year.", k: "mild" },
    { q: "The leaves are crisp in the ___ air.", k: "dry" },
    { q: "It's a bit ___ for swimming.", k: "chilly" },
    { q: "The sky is ___ and blue.", k: "clear" },
    { q: "We stayed home because of the ___.", k: "rain" },
    { q: "The ___ was strong enough to shake the house.", k: "wind" },
    { q: "Do you think it will ___ on Christmas?", k: "snow" },
    { q: "The mountains are hidden by ___.", k: "clouds" },
    { q: "She loves to sunbathe on ___ days.", k: "hot" },
    { q: "The ___ damaged many buildings.", k: "storm" },
    { q: "I can feel the ___ in the air.", k: "humidity" },
    { q: "The temperature dropped, and it became ___.", k: "cold" },
    { q: "The fog made it a very ___ morning.", k: "misty" },
    { q: "It's an ideal day for a picnic, very ___.", k: "pleasant" },
  ],
  aula4: [
    { q: "My ___ is the head of our family.", k: "father" },
    { q: "My ___ always bakes delicious cakes.", k: "mother" },
    { q: "I have one ___ and two sisters.", k: "brother" },
    { q: "My elder ___ lives in another city.", k: "sister" },
    { q: "My ___ is my mother's sister.", k: "aunt" },
    { q: "My ___ is the child of my aunt and uncle.", k: "cousin" },
    { q: "My ___ are coming to visit next week.", k: "parents" },
    { q: "My ___ is my father's brother.", k: "uncle" },
    { q: "My ___ is my mother's father.", k: "grandfather" },
    { q: "My ___ is my father's mother.", k: "grandmother" },
    { q: "I love spending time with my ___.", k: "grandparents" },
    { q: "My ___ is my brother's son.", k: "nephew" },
    { q: "My ___ is my sister's daughter.", k: "niece" },
    { q: "My ___ is the son of my child.", k: "grandson" },
    { q: "My ___ is the daughter of my child.", k: "granddaughter" },
    { q: "My ___ are my children's children.", k: "grandchildren" },
    { q: "My ___ is the husband of my daughter.", k: "son-in-law" },
    { q: "My ___ is the wife of my son.", k: "daughter-in-law" },
    { q: "My ___ is my husband's or wife's mother.", k: "mother-in-law" },
    { q: "My ___ is my husband's or wife's father.", k: "father-in-law" },
    { q: "My ___ is my husband's or wife's brother.", k: "brother-in-law" },
    { q: "My ___ is my husband's or wife's sister.", k: "sister-in-law" },
    { q: "We are a big ___ family.", k: "extended" },
    { q: "He has a close-knit ___.", k: "family" },
    { q: "She is the youngest ___ in the family.", k: "child" },
    { q: "They are celebrating their ___'s birthday.", k: "father's|fathers" },
    { q: "My ___ teaches at a school.", k: "mother" },
    { q: "I share a room with my ___.", k: "brother" },
    { q: "My ___ is getting married next month.", k: "sister" },
    { q: "We visited our ___ in the countryside.", k: "aunt" },
    { q: "My favorite ___ is always there for me.", k: "cousin" },
    { q: "They rely on their ___ for support.", k: "parents" },
    { q: "My ___ told us a funny story.", k: "uncle" },
    { q: "My ___ likes to tell stories about the past.", k: "grandfather" },
    { q: "My ___ is an amazing cook.", k: "grandmother" },
    { q: "The ___ enjoy playing with their toys.", k: "grandchildren" },
    { q: "My ___ just started university.", k: "niece" },
    { q: "My ___ is a keen sportsman.", k: "nephew" },
    { q: "He is very proud of his ___.", k: "son" },
    { q: "She is a loving ___.", k: "daughter" },
    { q: "We had a great time with our ___.", k: "relatives" },
    { q: "He is the oldest ___ in his family.", k: "sibling" },
    { q: "They are celebrating their ___ reunion.", k: "family" },
    { q: "My ___ is a great role model.", k: "father" },
    { q: "She is a wonderful ___ and friend.", k: "mother" },
    { q: "My ___ always helps me with my homework.", k: "brother" },
    { q: "I like to go shopping with my ___.", k: "sister" },
    { q: "My ___ is like a second mother to me.", k: "aunt" },
    { q: "We always have fun with our ___.", k: "cousins" },
    { q: "They are grateful for their ___'s support.", k: "parents'|parents" },
  ],
  aula5: [
    { q: "___ book is this? It's mine.", k: "Whose" },
    { q: "___ keys are these? They belong to John.", k: "Whose" },
    { q: "___ car is parked outside?", k: "Whose" },
    { q: "___ turn is it to play?", k: "Whose" },
    { q: "___ idea was it to go to the beach?", k: "Whose" },
    { q: "___ responsibility is this project?", k: "Whose" },
    { q: "___ cat is that? It's very fluffy.", k: "Whose" },
    { q: "___ phone is ringing?", k: "Whose" },
    { q: "___ children are playing in the garden?", k: "Whose" },
    { q: "___ coat is this on the chair?", k: "Whose" },
    { q: "___ house are we going to tonight?", k: "Whose" },
    { q: "___ decision was it to cancel the event?", k: "Whose" },
    { q: "___ opinion matters the most here?", k: "Whose" },
    { q: "___ bag did you find?", k: "Whose" },
    { q: "___ voice is that?", k: "Whose" },
    { q: "___ shoes are these?", k: "Whose" },
    { q: "___ advice should I follow?", k: "Whose" },
    { q: "___ dog is barking?", k: "Whose" },
    { q: "___ wallet was found?", k: "Whose" },
    { q: "___ turn is it to speak?", k: "Whose" },
    { q: "___ project is this?", k: "Whose" },
    { q: "___ umbrella is this?", k: "Whose" },
    { q: "___ fault was it?", k: "Whose" },
    { q: "___ car is in the garage?", k: "Whose" },
    { q: "___ pen is this on the table?", k: "Whose" },
    { q: "___ parents are visiting?", k: "Whose" },
    { q: "___ jacket is this?", k: "Whose" },
    { q: "___ book did you read?", k: "Whose" },
    { q: "___ idea was that?", k: "Whose" },
    { q: "___ bicycle is broken?", k: "Whose" },
    { q: "___ problem is this?", k: "Whose" },
    { q: "___ hat is this?", k: "Whose" },
    { q: "___ dreams are these?", k: "Whose" },
    { q: "___ backpack is this?", k: "Whose" },
    { q: "___ phone is charging?", k: "Whose" },
    { q: "___ tickets are these?", k: "Whose" },
    { q: "___ house is that?", k: "Whose" },
    { q: "___ painting is this?", k: "Whose" },
    { q: "___ choice was that?", k: "Whose" },
    { q: "___ song is this?", k: "Whose" },
    { q: "___ bag is this?", k: "Whose" },
    { q: "___ glasses are these?", k: "Whose" },
    { q: "___ dog is running around?", k: "Whose" },
    { q: "___ computer is this?", k: "Whose" },
    { q: "___ notes are these?", k: "Whose" },
    { q: "___ sister is she?", k: "Whose" },
    { q: "___ brother is he?", k: "Whose" },
    { q: "___ kids are playing?", k: "Whose" },
    { q: "___ coat is hanging here?", k: "Whose" },
    { q: "___ umbrella did you take?", k: "Whose" },
  ],
  aula6: [
    { q: "This is ___ book. (I)", k: "my" },
    { q: "That is ___ car. (you)", k: "your" },
    { q: "He gave me ___ phone number. (he)", k: "his" },
    { q: "She lost ___ keys. (she)", k: "her" },
    { q: "The dog wagged ___ tail. (it)", k: "its" },
    { q: "We like ___ new house. (we)", k: "our" },
    { q: "They brought ___ children. (they)", k: "their" },
    { q: "Is this ___ umbrella? (you)", k: "your" },
    { q: "This is ___ favorite song. (I)", k: "my" },
    { q: "He showed us ___ new car. (he)", k: "his" },
    { q: "She introduced ___ friend. (she)", k: "her" },
    { q: "The cat is eating ___ food. (it)", k: "its" },
    { q: "We finished ___ homework. (we)", k: "our" },
    { q: "They are proud of ___ achievements. (they)", k: "their" },
    { q: "Can I borrow ___ pen? (you)", k: "your" },
    { q: "I washed ___ hands. (I)", k: "my" },
    { q: "He polished ___ shoes. (he)", k: "his" },
    { q: "She brushed ___ hair. (she)", k: "her" },
    { q: "The bird returned to ___ nest. (it)", k: "its" },
    { q: "We packed ___ bags. (we)", k: "our" },
    { q: "They parked ___ bikes. (they)", k: "their" },
    { q: "What is ___ name? (you)", k: "your" },
    { q: "I love ___ family. (I)", k: "my" },
    { q: "He loves ___ dog. (he)", k: "his" },
    { q: "She loves ___ cat. (she)", k: "her" },
    { q: "The company announced ___ new policy. (it)", k: "its" },
    { q: "We cleaned ___ room. (we)", k: "our" },
    { q: "They sold ___ old car. (they)", k: "their" },
    { q: "Is this ___ decision? (you)", k: "your" },
    { q: "I read ___ book. (I)", k: "my" },
    { q: "He fixed ___ computer. (he)", k: "his" },
    { q: "She cooked ___ dinner. (she)", k: "her" },
    { q: "The tree lost ___ leaves. (it)", k: "its" },
    { q: "We celebrated ___ victory. (we)", k: "our" },
    { q: "They shared ___ food. (they)", k: "their" },
    { q: "Do you know ___ address? (you)", k: "your" },
    { q: "I finished ___ work. (I)", k: "my" },
    { q: "He bought ___ new jacket. (he)", k: "his" },
    { q: "She helped ___ mother. (she)", k: "her" },
    { q: "The team won ___ game. (it)", k: "its" },
    { q: "We visited ___ grandparents. (we)", k: "our" },
    { q: "They enjoy ___ vacation. (they)", k: "their" },
    { q: "Where is ___ phone? (you)", k: "your" },
    { q: "I forgot ___ wallet. (I)", k: "my" },
    { q: "He found ___ keys. (he)", k: "his" },
    { q: "She introduced ___ husband. (she)", k: "her" },
    { q: "The baby cried for ___ toy. (it)", k: "its" },
    { q: "We decorated ___ house. (we)", k: "our" },
    { q: "They cleaned ___ room. (they)", k: "their" },
    { q: "This is ___ problem. (I)", k: "my" },
  ],
  aula7: [
    { q: "___ is my pen. (near, singular)", k: "This" },
    { q: "___ are my shoes. (near, plural)", k: "These" },
    { q: "___ is your car. (far, singular)", k: "That" },
    { q: "___ are their books. (far, plural)", k: "Those" },
    { q: "Look at ___ bird in the sky. (far, singular)", k: "that" },
    { q: "Pass me ___ apples, please. (near, plural)", k: "these" },
    { q: "___ is an interesting idea. (near, singular)", k: "This" },
    { q: "___ cars are very fast. (far, plural)", k: "Those" },
    { q: "Can you see ___ mountains over there? (far, plural)", k: "those" },
    { q: "___ is a beautiful flower. (near, singular)", k: "This" },
    { q: "___ were the days! (far, plural)", k: "Those" },
    { q: "I don't like ___ color. (near, singular)", k: "this" },
    { q: "___ students are very clever. (near, plural)", k: "These" },
    { q: "Who is ___ man next to her? (far, singular)", k: "that" },
    { q: "___ are my favorite cookies. (near, plural)", k: "These" },
    { q: "___ was a mistake. (far, singular)", k: "That" },
    { q: "Please take ___ documents to the office. (near, plural)", k: "these" },
    { q: "Is ___ your jacket? (near, singular)", k: "this" },
    { q: "___ are not my keys. (near, plural)", k: "These" },
    { q: "___ is a difficult question. (near, singular)", k: "This" },
    { q: "___ children are making too much noise. (far, plural)", k: "Those" },
    { q: "I saw ___ movie last night. (far, singular)", k: "that" },
    { q: "___ is the best coffee. (near, singular)", k: "This" },
    { q: "___ are my friends. (near, plural)", k: "These" },
    { q: "Do you remember ___ day? (far, singular)", k: "that" },
    { q: "___ books on the shelf are old. (far, plural)", k: "Those" },
    { q: "Look at ___ beautiful painting! (near, singular)", k: "this" },
    { q: "___ are my new shoes. (near, plural)", k: "These" },
    { q: "___ was a great concert. (far, singular)", k: "That" },
    { q: "___ flowers are for you. (near, plural)", k: "These" },
    { q: "I don't want ___ one. (near, singular)", k: "this" },
    { q: "___ are interesting facts. (near, plural)", k: "These" },
    { q: "___ is her brother. (far, singular)", k: "That" },
    { q: "___ boys are playing football. (far, plural)", k: "Those" },
    { q: "Can I have ___ piece of cake? (near, singular)", k: "this" },
    { q: "___ are very useful tools. (near, plural)", k: "These" },
    { q: "___ was an amazing experience. (far, singular)", k: "That" },
    { q: "___ are expensive clothes. (far, plural)", k: "Those" },
    { q: "Is ___ your bag? (near, singular)", k: "this" },
    { q: "___ people are waiting for you. (far, plural)", k: "Those" },
    { q: "___ is not what I meant. (near, singular)", k: "This" },
    { q: "___ are delicious apples. (near, plural)", k: "These" },
    { q: "___ was a bad idea. (far, singular)", k: "That" },
    { q: "___ birds are singing. (near, plural)", k: "These" },
    { q: "Take ___ book with you. (near, singular)", k: "this" },
    { q: "___ are my parents. (near, plural)", k: "These" },
    { q: "___ is a beautiful day. (near, singular)", k: "This" },
    { q: "___ are lovely flowers. (near, plural)", k: "These" },
    { q: "___ was a long time ago. (far, singular)", k: "That" },
    { q: "___ are good memories. (far, plural)", k: "Those" },
  ],
  aula8: [
    { q: "I ___ (visit) my grandparents last weekend.", k: "visited" },
    { q: "She ___ (play) piano when she was a child.", k: "played" },
    { q: "They ___ (go) to the cinema yesterday.", k: "went" },
    { q: "He ___ (eat) pizza for dinner.", k: "ate" },
    { q: "We ___ (see) a great movie last night.", k: "saw" },
    { q: "She ___ (not / study) for the test.", k: "didn't study" },
    { q: "___ you ___ (finish) your homework? (Did)", k: "Did finish" },
    { q: "He ___ (write) a letter to his friend.", k: "wrote" },
    { q: "They ___ (arrive) late for the meeting.", k: "arrived" },
    { q: "I ___ (drink) a cup of tea this morning.", k: "drank" },
    { q: "She ___ (not / come) to the party.", k: "didn't come" },
    { q: "___ he ___ (call) you? (Did)", k: "Did call" },
    { q: "We ___ (have) a good time at the concert.", k: "had" },
    { q: "He ___ (buy) a new car last month.", k: "bought" },
    { q: "They ___ (speak) English in class.", k: "spoke" },
    { q: "She ___ (begin) her journey early.", k: "began" },
    { q: "I ___ (know) the answer yesterday.", k: "knew" },
    { q: "He ___ (tell) me a secret.", k: "told" },
    { q: "They ___ (find) their lost dog.", k: "found" },
    { q: "She ___ (forget) her umbrella.", k: "forgot" },
    { q: "We ___ (make) a cake for her birthday.", k: "made" },
    { q: "He ___ (take) a lot of photos.", k: "took" },
    { q: "They ___ (give) him a present.", k: "gave" },
    { q: "She ___ (run) in the marathon.", k: "ran" },
    { q: "I ___ (understand) the lesson.", k: "understood" },
    { q: "He ___ (sleep) for eight hours.", k: "slept" },
    { q: "They ___ (read) the whole book.", k: "read" },
    { q: "She ___ (sing) a beautiful song.", k: "sang" },
    { q: "We ___ (build) a treehouse.", k: "built" },
    { q: "He ___ (drive) to work.", k: "drove" },
    { q: "They ___ (eat) all the food.", k: "ate" },
    { q: "She ___ (see) her friend at the mall.", k: "saw" },
    { q: "I ___ (write) an essay.", k: "wrote" },
    { q: "He ___ (feel) sick yesterday.", k: "felt" },
    { q: "They ___ (break) the window.", k: "broke" },
    { q: "She ___ (get) a new job.", k: "got" },
    { q: "We ___ (come) home late.", k: "came" },
    { q: "He ___ (leave) his keys on the table.", k: "left" },
    { q: "They ___ (think) about their future.", k: "thought" },
    { q: "She ___ (lose) her wallet.", k: "lost" },
    { q: "I ___ (meet) her last week.", k: "met" },
    { q: "He ___ (sit) on the bench.", k: "sat" },
    { q: "They ___ (stand) in line.", k: "stood" },
    { q: "She ___ (teach) English for ten years.", k: "taught" },
    { q: "We ___ (win) the game.", k: "won" },
    { q: "He ___ (fly) to Paris.", k: "flew" },
    { q: "They ___ (swim) in the ocean.", k: "swam" },
    { q: "She ___ (hear) the news.", k: "heard" },
    { q: "I ___ (spend) my vacation in Brazil.", k: "spent" },
    { q: "He ___ (cut) the paper.", k: "cut" },
  ],
  aula14: [
    { q: "She ___ (go) to school every day.", k: "goes" },
    { q: "They ___ (play) soccer on weekends.", k: "play" },
    { q: "He ___ (study) English in the evening.", k: "studies" },
    { q: "We ___ (live) in a big city.", k: "live" },
    { q: "I ___ (drink) coffee every morning.", k: "drink" },
    { q: "The sun ___ (rise) in the east.", k: "rises" },
    { q: "Birds ___ (sing) in the morning.", k: "sing" },
    { q: "He ___ (watch) TV after dinner.", k: "watches" },
    { q: "They ___ (have) a big house.", k: "have" },
    { q: "She ___ (teach) mathematics.", k: "teaches" },
    { q: "We ___ (eat) breakfast at 7 AM.", k: "eat" },
    { q: "My cat ___ (sleep) all day.", k: "sleeps" },
    { q: "You ___ (work) very hard.", k: "work" },
    { q: "The train ___ (leave) at 8 o'clock.", k: "leaves" },
    { q: "He never ___ (forget) his keys.", k: "forgets" },
    { q: "They often ___ (visit) their grandparents.", k: "visit" },
    { q: "She ___ (read) a book before bed.", k: "reads" },
    { q: "We ___ (speak) English at work.", k: "speak" },
    { q: "I ___ (listen) to music while working.", k: "listen" },
    { q: "The dog ___ (bark) at strangers.", k: "barks" },
    { q: "He always ___ (help) his friends.", k: "helps" },
    { q: "They ___ (go) to the gym daily.", k: "go" },
    { q: "She ___ (cook) dinner every night.", k: "cooks" },
    { q: "We ___ (travel) every summer.", k: "travel" },
    { q: "I ___ (brush) my teeth twice a day.", k: "brush" },
    { q: "The baby ___ (cry) when he is hungry.", k: "cries" },
    { q: "He ___ (fix) cars for a living.", k: "fixes" },
    { q: "They ___ (enjoy) spending time together.", k: "enjoy" },
    { q: "She ___ (sing) beautifully.", k: "sing|sings" },
    { q: "We ___ (watch) movies on Fridays.", k: "watch" },
    { q: "I ___ (write) emails every morning.", k: "write" },
    { q: "The store ___ (open) at 9 AM.", k: "opens" },
    { q: "He ___ (finish) his work early.", k: "finishes" },
    { q: "They ___ (believe) in ghosts.", k: "believe" },
    { q: "She ___ (make) her own clothes.", k: "makes" },
    { q: "We ___ (study) hard for exams.", k: "study" },
    { q: "I ___ (love) chocolate.", k: "love" },
    { q: "The clock ___ (tick) loudly.", k: "ticks" },
    { q: "He ___ (drive) to work.", k: "drives" },
    { q: "They ___ (understand) the lesson.", k: "understand" },
    { q: "She ___ (start) work at 8 AM.", k: "starts" },
    { q: "We ___ (drink) a lot of water.", k: "drink" },
    { q: "I ___ (read) the newspaper daily.", k: "read" },
    { q: "The wind ___ (blow) strongly.", k: "blows" },
    { q: "He ___ (play) the piano.", k: "plays" },
    { q: "They ___ (walk) in the park.", k: "walk" },
    { q: "She ___ (clean) her room.", k: "cleans" },
    { q: "We ___ (learn) new things.", k: "learn" },
    { q: "I ___ (exercise) regularly.", k: "exercise" },
    { q: "The factory ___ (produce) cars.", k: "produces" },
  ],
  aula9: [
    { q: "I ___ (visit) my aunt tomorrow. (going to)", k: "am going to visit" },
    { q: "She ___ (buy) a new car next year. (will)", k: "will buy" },
    { q: "They ___ (travel) to Japan next month. (going to)", k: "are going to travel" },
    { q: "He ___ (not / come) to the party. (will)", k: "won't come" },
    { q: "We ___ (eat) dinner at 7 PM. (going to)", k: "are going to eat" },
    { q: "It ___ (rain) later. (will)", k: "will rain" },
    { q: "___ you ___ (help) me? (Will)", k: "Will help" },
    { q: "She ___ (start) a new job soon. (going to)", k: "is going to start" },
    { q: "They ___ (play) tennis this afternoon. (going to)", k: "are going to play" },
    { q: "I ___ (call) you back in 5 minutes. (will)", k: "will call" },
    { q: "He ___ (not / forget) your birthday. (will)", k: "won't forget" },
    { q: "We ___ (watch) a movie tonight. (going to)", k: "are going to watch" },
    { q: "The plane ___ (land) in 10 minutes. (will)", k: "will land" },
    { q: "She ___ (become) a doctor. (going to)", k: "is going to become" },
    { q: "They ___ (build) a new house. (going to)", k: "are going to build" },
    { q: "I ___ (open) the door for you. (will)", k: "will open" },
    { q: "He ___ (not / pass) the exam. (will)", k: "won't pass" },
    { q: "We ___ (have) a picnic this weekend. (going to)", k: "are going to have" },
    { q: "It ___ (be) cold tomorrow. (will)", k: "will be" },
    { q: "She ___ (meet) her friends later. (going to)", k: "is going to meet" },
    { q: "They ___ (learn) a new language. (going to)", k: "are going to learn" },
    { q: "I ___ (help) you with your bags. (will)", k: "will help" },
    { q: "He ___ (not / win) the race. (will)", k: "won't win" },
    { q: "We ___ (cook) pasta tonight. (going to)", k: "are going to cook" },
    { q: "The store ___ (close) at 9 PM. (will)", k: "will close" },
    { q: "She ___ (travel) around the world. (going to)", k: "is going to travel" },
    { q: "They ___ (start) their business soon. (going to)", k: "are going to start" },
    { q: "I ___ (send) you an email. (will)", k: "will send" },
    { q: "He ___ (not / finish) on time. (will)", k: "won't finish" },
    { q: "We ___ (buy) a new sofa. (going to)", k: "are going to buy" },
    { q: "It ___ (snow) next week. (will)", k: "will snow" },
    { q: "She ___ (read) that book. (going to)", k: "is going to read" },
    { q: "They ___ (move) to a new city. (going to)", k: "are going to move" },
    { q: "I ___ (tell) you a secret. (will)", k: "will tell" },
    { q: "He ___ (not / like) the present. (will)", k: "won't like" },
    { q: "We ___ (celebrate) her birthday. (going to)", k: "are going to celebrate" },
    { q: "The movie ___ (start) at 8 PM. (will)", k: "will start" },
    { q: "She ___ (paint) her room. (going to)", k: "is going to paint" },
    { q: "They ___ (repair) the car. (going to)", k: "are going to repair" },
    { q: "I ___ (bring) some snacks. (will)", k: "will bring" },
    { q: "He ___ (not / study) for the test. (will)", k: "won't study" },
    { q: "We ___ (visit) the museum. (going to)", k: "are going to visit" },
    { q: "It ___ (be) sunny tomorrow. (will)", k: "will be" },
    { q: "She ___ (learn) to play guitar. (going to)", k: "is going to learn" },
    { q: "They ___ (clean) the house. (going to)", k: "are going to clean" },
    { q: "I ___ (answer) your question. (will)", k: "will answer" },
    { q: "He ___ (not / listen) to you. (will)", k: "won't listen" },
    { q: "We ___ (watch) the football game. (going to)", k: "are going to watch" },
    { q: "The show ___ (end) soon. (will)", k: "will end" },
    { q: "She ___ (help) her brother. (going to)", k: "is going to help" },
  ],
  aula10: [
    { q: "I ___ (study) English right now.", k: "am studying" },
    { q: "She ___ (read) a book at the moment.", k: "is reading" },
    { q: "They ___ (play) soccer in the park.", k: "are playing" },
    { q: "He ___ (not / work) today.", k: "isn't working" },
    { q: "We ___ (eat) dinner together.", k: "are eating" },
    { q: "It ___ (rain) heavily outside.", k: "is raining" },
    { q: "___ you ___ (listen) to music? (Are)", k: "Are listening" },
    { q: "She ___ (write) an email.", k: "is writing" },
    { q: "They ___ (watch) TV.", k: "are watching" },
    { q: "I ___ (wait) for the bus.", k: "am waiting" },
    { q: "He ___ (talk) on the phone.", k: "is talking" },
    { q: "We ___ (learn) a new language.", k: "are learning" },
    { q: "The birds ___ (sing) beautifully.", k: "are singing" },
    { q: "She ___ (cook) lunch.", k: "is cooking" },
    { q: "They ___ (dance) at the party.", k: "are dancing" },
    { q: "I ___ (clean) my room.", k: "am cleaning" },
    { q: "He ___ (sleep) in his bed.", k: "is sleeping" },
    { q: "We ___ (have) a good time.", k: "are having" },
    { q: "The dog ___ (bark) at the mailman.", k: "is barking" },
    { q: "She ___ (run) in the park.", k: "is running" },
    { q: "They ___ (build) a new house.", k: "are building" },
    { q: "I ___ (drink) water.", k: "am drinking" },
    { q: "He ___ (draw) a picture.", k: "is drawing" },
    { q: "We ___ (walk) to school.", k: "are walking" },
    { q: "The baby ___ (cry).", k: "is crying" },
    { q: "She ___ (help) her mother.", k: "is helping" },
    { q: "They ___ (shop) for groceries.", k: "are shopping" },
    { q: "I ___ (listen) to the radio.", k: "am listening" },
    { q: "He ___ (play) guitar.", k: "is playing" },
    { q: "We ___ (study) for our exams.", k: "are studying" },
    { q: "The sun ___ (shine).", k: "is shining" },
    { q: "She ___ (eat) an apple.", k: "is eating" },
    { q: "They ___ (swim) in the pool.", k: "are swimming" },
    { q: "I ___ (talk) to my friend.", k: "am talking" },
    { q: "He ___ (write) a letter.", k: "is writing" },
    { q: "We ___ (go) to the cinema.", k: "are going" },
    { q: "The chef ___ (cook) a delicious meal.", k: "is cooking" },
    { q: "She ___ (sing) a song.", k: "is singing" },
    { q: "They ___ (work) on a project.", k: "are working" },
    { q: "I ___ (sit) on the chair.", k: "am sitting" },
    { q: "He ___ (read) the newspaper.", k: "is reading" },
    { q: "We ___ (travel) around the world.", k: "are traveling" },
    { q: "The kids ___ (play) with toys.", k: "are playing" },
    { q: "She ___ (take) a picture.", k: "is taking" },
    { q: "They ___ (wait) for you.", k: "are waiting" },
    { q: "I ___ (think) about my vacation.", k: "am thinking" },
    { q: "He ___ (clean) the kitchen.", k: "is cleaning" },
    { q: "We ___ (plan) our trip.", k: "are planning" },
    { q: "The wind ___ (blow) gently.", k: "is blowing" },
    { q: "She ___ (watch) a documentary.", k: "is watching" },
  ],
  aula11: [
    { q: "I ___ (read) a book when you called.", k: "was reading" },
    { q: "She ___ (sleep) when the phone rang.", k: "was sleeping" },
    { q: "They ___ (play) outside all afternoon.", k: "were playing" },
    { q: "He ___ (not / listen) to me.", k: "wasn't listening" },
    { q: "We ___ (eat) dinner at 8 PM yesterday.", k: "were eating" },
    { q: "It ___ (rain) when I woke up.", k: "was raining" },
    { q: "___ you ___ (watch) TV? (Were)", k: "Were watching" },
    { q: "She ___ (sing) a song while she was cooking.", k: "was singing" },
    { q: "They ___ (study) for their exam.", k: "were studying" },
    { q: "I ___ (wait) for him at the cafe.", k: "was waiting" },
    { q: "He ___ (work) on his computer.", k: "was working" },
    { q: "We ___ (talk) about our plans.", k: "were talking" },
    { q: "The children ___ (run) in the garden.", k: "were running" },
    { q: "She ___ (clean) her room all morning.", k: "was cleaning" },
    { q: "They ___ (dance) when the music stopped.", k: "were dancing" },
    { q: "I ___ (cook) when the electricity went out.", k: "was cooking" },
    { q: "He ___ (drive) to work when he saw the accident.", k: "was driving" },
    { q: "We ___ (listen) to the radio.", k: "were listening" },
    { q: "The dog ___ (bark) loudly.", k: "was barking" },
    { q: "She ___ (write) an article for the newspaper.", k: "was writing" },
    { q: "They ___ (build) a sandcastle on the beach.", k: "were building" },
    { q: "I ___ (drink) tea when she arrived.", k: "was drinking" },
    { q: "He ___ (draw) a landscape.", k: "was drawing" },
    { q: "We ___ (walk) in the park when it started to rain.", k: "were walking" },
    { q: "The baby ___ (sleep) peacefully.", k: "was sleeping" },
    { q: "She ___ (help) her neighbor.", k: "was helping" },
    { q: "They ___ (shop) at the mall.", k: "were shopping" },
    { q: "I ___ (watch) a movie on Netflix.", k: "was watching" },
    { q: "He ___ (play) video games.", k: "was playing" },
    { q: "We ___ (have) a party.", k: "were having" },
    { q: "The sun ___ (set) beautifully.", k: "was setting" },
    { q: "She ___ (eat) breakfast.", k: "was eating" },
    { q: "They ___ (swim) in the lake.", k: "were swimming" },
    { q: "I ___ (talk) on the phone.", k: "was talking" },
    { q: "He ___ (read) an interesting article.", k: "was reading" },
    { q: "We ___ (go) to the concert.", k: "were going" },
    { q: "The wind ___ (blow) strongly.", k: "was blowing" },
    { q: "She ___ (do) her homework.", k: "was doing" },
    { q: "They ___ (work) on their project.", k: "were working" },
    { q: "I ___ (sit) in the garden.", k: "was sitting" },
    { q: "He ___ (listen) to music.", k: "was listening" },
    { q: "We ___ (plan) our vacation.", k: "were planning" },
    { q: "The students ___ (take) a test.", k: "were taking" },
    { q: "She ___ (prepare) for the presentation.", k: "was preparing" },
    { q: "They ___ (discuss) the new policy.", k: "were discussing" },
    { q: "I ___ (think) about you.", k: "was thinking" },
    { q: "He ___ (repair) his bicycle.", k: "was repairing" },
    { q: "We ___ (wait) for the results.", k: "were waiting" },
    { q: "The teacher ___ (explain) the lesson.", k: "was explaining" },
    { q: "She ___ (look) for her keys.", k: "was looking" },
  ],
  aula12: [
    { q: "She gave the book to ___ (I).", k: "me" },
    { q: "I saw ___ at the party. (you)", k: "you" },
    { q: "We invited ___ to dinner. (he)", k: "him" },
    { q: "He talked to ___ about the problem. (she)", k: "her" },
    { q: "The dog followed ___. (it)", k: "it" },
    { q: "She helped ___ with our homework. (we)", k: "us" },
    { q: "I called ___ yesterday. (they)", k: "them" },
    { q: "Can you pass ___ the salt? (I)", k: "me" },
    { q: "The teacher asked ___ a question. (you)", k: "you" },
    { q: "I sent ___ an email. (he)", k: "him" },
    { q: "He gave ___ a present. (she)", k: "her" },
    { q: "The cat looked at ___. (it)", k: "it" },
    { q: "She brought flowers for ___. (we)", k: "us" },
    { q: "We visited ___ last summer. (they)", k: "them" },
    { q: "Tell ___ the truth. (I)", k: "me" },
    { q: "I can help ___ with that. (you)", k: "you" },
    { q: "She loves ___. (he)", k: "him" },
    { q: "He misses ___. (she)", k: "her" },
    { q: "Don't touch ___. (it)", k: "it" },
    { q: "He told ___ a secret. (we)", k: "us" },
    { q: "They saw ___ at the concert. (I)", k: "me" },
    { q: "I need to talk to ___. (you)", k: "you" },
    { q: "Give ___ the money. (he)", k: "him" },
    { q: "I saw ___ at the store. (she)", k: "her" },
    { q: "He kicked ___. (it - ball)", k: "it" },
    { q: "She cooked dinner for ___. (we)", k: "us" },
    { q: "We played with ___ in the park. (they)", k: "them" },
    { q: "Can you hear ___? (I)", k: "me" },
    { q: "I believe ___. (you)", k: "you" },
    { q: "She called ___. (he)", k: "him" },
    { q: "He thanked ___. (she)", k: "her" },
    { q: "The dog licked ___. (it)", k: "it" },
    { q: "They joined ___. (we)", k: "us" },
    { q: "I followed ___. (they)", k: "them" },
    { q: "Please explain ___ again. (I)", k: "me" },
    { q: "Are you talking to ___? (you)", k: "me" },
    { q: "She waved at ___. (he)", k: "him" },
    { q: "He looked at ___. (she)", k: "her" },
    { q: "The bird watched ___. (it)", k: "it" },
    { q: "They offered ___ a ride. (we)", k: "us" },
    { q: "We waited for ___. (they)", k: "them" },
    { q: "I understood ___. (you)", k: "you" },
    { q: "She spoke to ___. (he)", k: "him" },
    { q: "He listened to ___. (she)", k: "her" },
    { q: "The car hit ___. (it - tree)", k: "it" },
    { q: "They sent ___ a postcard. (we)", k: "us" },
    { q: "I helped ___. (they)", k: "them" },
    { q: "Can you see ___? (I)", k: "me" },
    { q: "I like ___. (you)", k: "you" },
    { q: "She likes ___. (he)", k: "him" },
  ],
  aula13: [
    { q: "The movie was ___ good.", k: "very" },
    { q: "I am ___ tired today.", k: "really" },
    { q: "It's ___ hot outside.", k: "so" },
    { q: "This coffee is ___ hot to drink.", k: "too" },
    { q: "She is ___ beautiful.", k: "very" },
    { q: "He is ___ intelligent.", k: "really" },
    { q: "The test was ___ difficult.", k: "so" },
    { q: "The music is ___ loud.", k: "too" },
    { q: "I am ___ happy to see you.", k: "very" },
    { q: "It was ___ cold yesterday.", k: "really" },
    { q: "The book was ___ interesting.", k: "so" },
    { q: "This bag is ___ heavy for me.", k: "too" },
    { q: "She is a ___ good student.", k: "very" },
    { q: "He drives ___ fast.", k: "really" },
    { q: "The food was ___ delicious.", k: "so" },
    { q: "It's ___ late to go out.", k: "too" },
    { q: "I feel ___ relaxed after the massage.", k: "very" },
    { q: "The news was ___ shocking.", k: "really" },
    { q: "You are ___ kind.", k: "so" },
    { q: "He is ___ young to drive.", k: "too" },
    { q: "The view is ___ amazing.", k: "very" },
    { q: "She is ___ talented.", k: "really" },
    { q: "I am ___ sorry.", k: "so" },
    { q: "It's ___ dark in here.", k: "too" },
    { q: "This is a ___ important meeting.", k: "very" },
    { q: "He is ___ strong.", k: "really" },
    { q: "The movie was ___ sad.", k: "so" },
    { q: "This puzzle is ___ difficult.", k: "too" },
    { q: "She is ___ excited about her trip.", k: "very" },
    { q: "The concert was ___ good.", k: "really" },
    { q: "It's ___ beautiful outside.", k: "so" },
    { q: "He talks ___ much.", k: "too" },
    { q: "I am ___ grateful for your help.", k: "very" },
    { q: "The performance was ___ impressive.", k: "really" },
    { q: "You are ___ sweet.", k: "so" },
    { q: "She is ___ busy to talk.", k: "too" },
    { q: "This is ___ delicious.", k: "very" },
    { q: "The car is ___ expensive.", k: "really" },
    { q: "I am ___ happy for you.", k: "so" },
    { q: "It's ___ risky.", k: "too" },
    { q: "She is ___ intelligent.", k: "very" },
    { q: "He is ___ funny.", k: "really" },
    { q: "The news was ___ exciting.", k: "so" },
    { q: "It's ___ early to leave.", k: "too" },
    { q: "I am ___ disappointed.", k: "very" },
    { q: "She is ___ shy.", k: "really" },
    { q: "You are ___ amazing.", k: "so" },
    { q: "He is ___ sensitive.", k: "too" },
    { q: "This is ___ interesting.", k: "very" },
    { q: "The weather is ___ bad.", k: "really" },
  ],
  aula15: [
    { q: "___ is your name?", k: "What" },
    { q: "___ do you live?", k: "Where" },
    { q: "___ is your favorite color?", k: "What" },
    { q: "___ do you go to bed?", k: "When" },
    { q: "___ is he? He is my brother.", k: "Who" },
    { q: "___ do you want to eat?", k: "What" },
    { q: "___ is your birthday?", k: "When" },
    { q: "___ is the capital of France?", k: "What" },
    { q: "___ did you buy that?", k: "Where" },
    { q: "___ is your teacher?", k: "Who" },
    { q: "___ are you crying?", k: "Why" },
    { q: "___ old are you?", k: "How" },
    { q: "___ time is it?", k: "What" },
    { q: "___ did you arrive?", k: "When" },
    { q: "___ is your favorite animal?", k: "What" },
    { q: "___ are you going?", k: "Where" },
    { q: "___ is she? She is my mother.", k: "Who" },
    { q: "___ do you like it?", k: "Why" },
    { q: "___ do you go to school?", k: "How" },
    { q: "___ is your favorite food?", k: "What" },
    { q: "___ did you meet him?", k: "When" },
    { q: "___ is your address?", k: "Where" },
    { q: "___ is your best friend?", k: "Who" },
    { q: "___ are you laughing?", k: "Why" },
    { q: "___ many books do you have?", k: "How" },
    { q: "___ kind of music do you listen to?", k: "What" },
    { q: "___ did you learn English?", k: "When" },
    { q: "___ is the nearest bus stop?", k: "Where" },
    { q: "___ broke the window?", k: "Who" },
    { q: "___ are you sad?", k: "Why" },
    { q: "___ do you feel?", k: "How" },
    { q: "___ subject do you like the most?", k: "What" },
    { q: "___ did the accident happen?", k: "When" },
    { q: "___ is your car?", k: "Where" },
    { q: "___ is the new student?", k: "Who" },
    { q: "___ did you do that?", k: "Why" },
    { q: "___ much does it cost?", k: "How" },
    { q: "___ movie did you watch?", k: "What" },
    { q: "___ did you come here?", k: "When" },
    { q: "___ is your workplace?", k: "Where" },
    { q: "___ is your favorite actor?", k: "Who" },
    { q: "___ are you so happy?", k: "Why" },
    { q: "___ do you spell your name?", k: "How" },
    { q: "___ sports do you play?", k: "What" },
    { q: "___ did you last see him?", k: "When" },
    { q: "___ is your school?", k: "Where" },
    { q: "___ is calling me?", k: "Who" },
    { q: "___ did you choose this?", k: "Why" },
    { q: "___ was the weather like?", k: "How" },
    { q: "___ is your favorite hobby?", k: "What" },
  ],
  aula16: [
    { q: "I need to ___ my old clothes. (donate/throw away)", k: "give up" },
    { q: "Can you ___ the music? It's too loud. (reduce volume)", k: "turn down" },
    { q: "She decided to ___ smoking. (stop)", k: "give up" },
    { q: "We need to ___ early tomorrow. (start a journey)", k: "set off" },
    { q: "He will ___ the problem. (investigate)", k: "look into" },
    { q: "Don't forget to ___ the lights when you leave. (extinguish)", k: "turn off" },
    { q: "I ___ my keys this morning. (find by chance)", k: "came across" },
    { q: "She always ___ her promises. (fulfill)", k: "carries out" },
    { q: "They ___ a new plan. (invent/create)", k: "came up with" },
    { q: "He needs to ___ his grades. (improve)", k: "bring up" },
    { q: "We need to ___ our differences. (resolve)", k: "work out" },
    { q: "She decided to ___ running. (start a hobby)", k: "take up" },
    { q: "Can you ___ what he said? (understand)", k: "make out" },
    { q: "I will ___ you at the airport. (collect)", k: "pick up" },
    { q: "They ___ because of the bad weather. (cancel)", k: "called off" },
    { q: "He ___ his old friend at the mall. (meet by chance)", k: "ran into" },
    { q: "She needs to ___ her children. (raise)", k: "bring up" },
    { q: "We will ___ the celebration until next week. (postpone)", k: "put off" },
    { q: "The police are ___ the case. (investigating)", k: "looking into" },
    { q: "Please ___ the form. (complete)", k: "fill out" },
    { q: "He wants to ___ a new business. (establish)", k: "set up" },
    { q: "She likes to ___ new challenges. (accept)", k: "take on" },
    { q: "They need to ___ the rules. (obey)", k: "abide by" },
    { q: "I will ___ my promise. (keep)", k: "carry out" },
    { q: "He had to ___ his trip. (cancel)", k: "call off" },
    { q: "She ___ an old photograph. (discover by chance)", k: "came across" },
    { q: "We need to ___ a solution. (find)", k: "come up with" },
    { q: "Can you ___ the TV? (increase volume)", k: "turn up" },
    { q: "Don't ___ on your dreams. (abandon)", k: "give up" },
    { q: "They ___ their new project next month. (begin)", k: "kick off" },
    { q: "He always ___ his word. (keep)", k: "stands by" },
    { q: "She needs to ___ after her younger sister. (take care of)", k: "look after" },
    { q: "We need to ___ the issue. (discuss)", k: "talk over" },
    { q: "I will ___ the application form. (submit)", k: "hand in" },
    { q: "He had to ___ a lot of challenges. (face)", k: "deal with" },
    { q: "She needs to ___ her past. (forget)", k: "get over" },
    { q: "They decided to ___ early. (leave)", k: "set off" },
    { q: "I will ___ you later. (call)", k: "call back" },
    { q: "He had to ___ to his parents' demands. (yield)", k: "give in" },
    { q: "She will ___ her best to succeed. (try)", k: "do her best|do her best" },
    { q: "We need to ___ the report by Friday. (complete)", k: "hand in" },
    { q: "He will ___ the problem to his manager. (explain)", k: "point out" },
    { q: "She likes to ___ new ideas. (experiment with)", k: "try out" },
    { q: "They decided to ___ their differences. (settle)", k: "sort out" },
    { q: "I need to ___ the details. (verify)", k: "check out" },
    { q: "He will ___ his responsibilities. (avoid)", k: "get out of" },
    { q: "She likes to ___ on old friends. (visit informally)", k: "call on" },
    { q: "We need to ___ for the meeting. (prepare)", k: "get ready" },
    { q: "He will ___ his promises. (fail to keep)", k: "break his promises|break his word" },
    { q: "She will ___ the new system. (test)", k: "try out" },
  ],
};
