export const exerciseData = {
  aula1: [
    { q: "Yesterday I ___ very tired.", k: "was", t: "Ontem eu estava muito cansado." },
    { q: "They ___ at the park last weekend.", k: "were", t: "Eles estavam no parque no último fim de semana." },
    { q: "She ___ happy to see him.", k: "was", t: "Ela estava feliz em vê-lo." },
    { q: "We ___ not at home yesterday evening.", k: "were", t: "Nós não estávamos em casa ontem à noite." },
    { q: "He ___ a student last year.", k: "was", t: "Ele era um estudante no ano passado." },
    { q: "You ___ late for the meeting.", k: "were", t: "Você estava atrasado para a reunião." },
    { q: "It ___ a sunny day.", k: "was", t: "Estava um dia ensolarado." },
    { q: "My parents ___ on vacation.", k: "were", t: "Meus pais estavam de férias." },
    { q: "I ___ sick yesterday.", k: "was", t: "Eu estava doente ontem." },
    { q: "The kids ___ noisy.", k: "were", t: "As crianças estavam barulhentas." },
    { q: "She ___ a doctor.", k: "was", t: "Ela era médica." },
    { q: "We ___ friends in high school.", k: "were", t: "Nós éramos amigos no ensino médio." },
    { q: "He ___ in London last month.", k: "was", t: "Ele estava em Londres no mês passado." },
    { q: "You ___ right.", k: "were", t: "Você estava certo." },
    { q: "It ___ cold this morning.", k: "was", t: "Estava frio esta manhã." },
    { q: "They ___ busy.", k: "were", t: "Eles estavam ocupados." },
    { q: "I ___ at the office.", k: "was", t: "Eu estava no escritório." },
    { q: "She ___ beautiful.", k: "was", t: "Ela estava linda." },
    { q: "We ___ hungry.", k: "were", t: "Nós estávamos com fome." },
    { q: "He ___ smart.", k: "was", t: "Ele era inteligente." },
    { q: "You ___ a good student.", k: "were", t: "Você era um bom estudante." },
    { q: "It ___ interesting.", k: "was", t: "Era interessante." },
    { q: "They ___ sad.", k: "were", t: "Eles estavam tristes." },
    { q: "I ___ excited.", k: "was", t: "Eu estava animado." },
    { q: "She ___ tall.", k: "was", t: "Ela era alta." },
    { q: "We ___ together.", k: "were", t: "Nós estávamos juntos." },
    { q: "He ___ kind.", k: "was", t: "Ele era gentil." },
    { q: "You ___ lucky.", k: "were", t: "Você teve sorte." },
    { q: "It ___ easy.", k: "was", t: "Era fácil." },
    { q: "They ___ tired.", k: "were", t: "Eles estavam cansados." },
    { q: "I ___ happy.", k: "was", t: "Eu estava feliz." },
    { q: "She ___ brave.", k: "was", t: "Ela era corajosa." },
    { q: "We ___ confused.", k: "were", t: "Nós estávamos confusos." },
    { q: "He ___ strong.", k: "was", t: "Ele era forte." },
    { q: "You ___ amazing.", k: "were", t: "Você era incrível." },
    { q: "It ___ difficult.", k: "was", t: "Era difícil." },
    { q: "They ___ surprised.", k: "were", t: "Eles estavam surpresos." },
    { q: "I ___ curious.", k: "was", t: "Eu estava curioso." },
    { q: "She ___ quiet.", k: "was", t: "Ela estava quieta." },
    { q: "We ___ prepared.", k: "were", t: "Nós estávamos preparados." },
    { q: "He ___ calm.", k: "was", t: "Ele estava calmo." },
    { q: "You ___ thoughtful.", k: "were", t: "Você foi atencioso." },
    { q: "It ___ challenging.", k: "was", t: "Era desafiador." },
    { q: "They ___ early.", k: "were", t: "Eles chegaram cedo." },
    { q: "I ___ late.", k: "was", t: "Eu estava atrasado." },
    { q: "She ___ patient.", k: "was", t: "Ela era paciente." },
    { q: "We ___ determined.", k: "were", t: "Nós estávamos determinados." },
    { q: "He ___ focused.", k: "was", t: "Ele estava focado." },
    { q: "You ___ inspired.", k: "were", t: "Você estava inspirado." },
    { q: "It ___ quick.", k: "was", t: "Foi rápido." },
  ],
  aula2: [
    { q: "My car is ___ than yours. (fast)", k: "faster", t: "Meu carro é mais rápido que o seu." },
    { q: "She is ___ than her brother. (tall)", k: "taller", t: "Ela é mais alta que o irmão dela." },
    { q: "This book is ___ than that one. (interesting)", k: "more interesting", t: "Este livro é mais interessante que aquele." },
    { q: "He is ___ at math than me. (good)", k: "better", t: "Ele é melhor em matemática do que eu." },
    { q: "The weather today is ___ than yesterday. (cold)", k: "colder", t: "O clima hoje está mais frio que ontem." },
    { q: "Learning English is ___ than learning Chinese. (easy)", k: "easier", t: "Aprender inglês é mais fácil que aprender chinês." },
    { q: "This sofa is ___ than the chair. (comfortable)", k: "more comfortable", t: "Este sofá é mais confortável que a cadeira." },
    { q: "He runs ___ than his friend. (quickly)", k: "more quickly", t: "Ele corre mais rápido que o amigo dele." },
    { q: "Her house is ___ than mine. (big)", k: "bigger", t: "A casa dela é maior que a minha." },
    { q: "The new movie is ___ than the old one. (exciting)", k: "more exciting", t: "O filme novo é mais emocionante que o antigo." },
    { q: "My phone is ___ than yours. (expensive)", k: "more expensive", t: "Meu telefone é mais caro que o seu." },
    { q: "She sings ___ than anyone else. (beautifully)", k: "more beautifully", t: "Ela canta mais lindamente do que qualquer outra pessoa." },
    { q: "This exercise is ___ than the last one. (difficult)", k: "more difficult", t: "Este exercício é mais difícil que o anterior." },
    { q: "He works ___ than his colleagues. (hard)", k: "harder", t: "Ele trabalha mais duro que os colegas dele." },
    { q: "The blue dress is ___ than the red one. (pretty)", k: "prettier", t: "O vestido azul é mais bonito que o vermelho." },
    { q: "The city is ___ than the countryside. (noisy)", k: "noisier", t: "A cidade é mais barulhenta que o campo." },
    { q: "His ideas are ___ than hers. (creative)", k: "more creative", t: "As ideias dele são mais criativas que as dela." },
    { q: "The journey was ___ than we expected. (long)", k: "longer", t: "A jornada foi mais longa do que esperávamos." },
    { q: "She is ___ in her studies. (diligent)", k: "more diligent", t: "Ela é mais diligente em seus estudos." },
    { q: "This restaurant is ___ than that one. (popular)", k: "more popular", t: "Este restaurante é mais popular que aquele." },
    { q: "The test was ___ than I thought. (easy)", k: "easier", t: "O teste foi mais fácil do que eu pensava." },
    { q: "He drives ___ than his wife. (carefully)", k: "more carefully", t: "Ele dirige mais cuidadosamente que a esposa dele." },
    { q: "The new system is ___ than the old one. (efficient)", k: "more efficient", t: "O novo sistema é mais eficiente que o antigo." },
    { q: "My new job is ___ than my previous one. (stressful)", k: "more stressful", t: "Meu novo emprego é mais estressante que o anterior." },
    { q: "She arrived ___ than him. (early)", k: "earlier", t: "Ela chegou mais cedo que ele." },
    { q: "This painting is ___ than the other. (colorful)", k: "more colorful", t: "Esta pintura é mais colorida que a outra." },
    { q: "He is ___ at playing guitar. (bad)", k: "worse", t: "Ele é pior em tocar violão." },
    { q: "The summer is ___ than the winter. (hot)", k: "hotter", t: "O verão é mais quente que o inverno." },
    { q: "His car is ___ than mine. (old)", k: "older", t: "O carro dele é mais velho que o meu." },
    { q: "This task is ___ than the previous one. (important)", k: "more important", t: "Esta tarefa é mais importante que a anterior." },
    { q: "She speaks English ___ than her sister. (fluently)", k: "more fluently", t: "Ela fala inglês mais fluentemente que a irmã dela." },
    { q: "The new phone is ___ than the old model. (sleek)", k: "sleeker", t: "O novo telefone é mais elegante que o modelo antigo." },
    { q: "He seems ___ than before. (happy)", k: "happier", t: "Ele parece mais feliz do que antes." },
    { q: "The food here is ___ than at that place. (good)", k: "better", t: "A comida aqui é melhor do que naquele lugar." },
    { q: "The problem became ___ over time. (complicated)", k: "more complicated", t: "O problema se tornou mais complicado com o tempo." },
    { q: "Our team played ___ today. (well)", k: "better", t: "Nosso time jogou melhor hoje." },
    { q: "The concert was ___ than the movie. (loud)", k: "louder", t: "O concerto foi mais alto que o filme." },
    { q: "Her explanation was ___ than his. (clear)", k: "clearer", t: "A explicação dela foi mais clara que a dele." },
    { q: "This project is ___ than the last one. (challenging)", k: "more challenging", t: "Este projeto é mais desafiador que o anterior." },
    { q: "The garden is ___ now. (beautiful)", k: "more beautiful", t: "O jardim está mais bonito agora." },
    { q: "He works ___ hours than I do. (long)", k: "longer", t: "Ele trabalha mais horas do que eu." },
    { q: "She writes ___ than anyone else. (creatively)", k: "more creatively", t: "Ela escreve mais criativamente do que qualquer outra pessoa." },
    { q: "The test was ___ than I expected. (hard)", k: "harder", t: "O teste foi mais difícil do que eu esperava." },
    { q: "This coffee is ___ than the one from Starbucks. (good)", k: "better", t: "Este café é melhor do que o da Starbucks." },
    { q: "His house is ___ than mine. (far)", k: "farther", t: "A casa dele é mais longe que a minha." },
    { q: "The lecture was ___ than the book. (informative)", k: "more informative", t: "A palestra foi mais informativa que o livro." },
    { q: "She is ___ with her hands. (skillful)", k: "more skillful", t: "Ela é mais habilidosa com as mãos." },
    { q: "The weather is getting ___ every day. (warm)", k: "warmer", t: "O tempo está ficando mais quente a cada dia." },
    { q: "His argument was ___ than hers. (convincing)", k: "more convincing", t: "O argumento dele foi mais convincente que o dela." },
    { q: "The movie was ___ than the book. (boring)", k: "more boring", t: "O filme foi mais chato que o livro." },
  ],
  aula3: [
    { q: "It's very ___ today, wear a jacket!", k: "cold", t: "Está muito frio hoje, use uma jaqueta!" },
    { q: "The sun is shining, it's a ___ day.", k: "sunny", t: "O sol está brilhando, está um dia ensolarado." },
    { q: "Don't forget your umbrella, it's ___ outside.", k: "rainy", t: "Não esqueça seu guarda-chuva, está chuvoso lá fora." },
    { q: "The trees are moving a lot, it's ___.", k: "windy", t: "As árvores estão se movendo muito, está ventando." },
    { q: "It might ___ tonight, so be careful on the roads.", k: "snowy", t: "Pode nevar esta noite, então tome cuidado nas estradas." },
    { q: "It's so ___ that I can't see the sky.", k: "cloudy", t: "Está tão nublado que não consigo ver o céu." },
    { q: "I love summer, it's always ___ and bright.", k: "hot", t: "Eu amo o verão, é sempre quente e claro." },
    { q: "The forecast says it will be ___ tomorrow.", k: "stormy", t: "A previsão diz que estará tempestuoso amanhã." },
    { q: "After the rain, it became very ___.", k: "humid", t: "Depois da chuva, ficou muito úmido." },
    { q: "It's a beautiful ___ autumn day.", k: "mild", t: "É um lindo dia de outono ameno." },
    { q: "The ___ in the desert is extreme.", k: "dry", t: "A secura no deserto é extrema." },
    { q: "It's ___ outside, I need a sweater.", k: "chilly", t: "Está frio lá fora, preciso de um suéter." },
    { q: "The sky is ___ and clear.", k: "clear", t: "O céu está limpo e claro." },
    { q: "We had a ___ shower this morning.", k: "light rain|lightrain", t: "Tivemos uma chuva leve esta manhã." },
    { q: "There's a strong ___ blowing.", k: "wind", t: "Está ventando muito." },
    { q: "The mountains are covered in ___.", k: "snow", t: "As montanhas estão cobertas de neve." },
    { q: "It's freezing ___ today.", k: "cold", t: "Está congelando hoje." },
    { q: "I prefer ___ days for a walk.", k: "sunny", t: "Prefiro dias ensolarados para uma caminhada." },
    { q: "The ___ season is long here.", k: "rainy", t: "A estação chuvosa é longa aqui." },
    { q: "The ___ makes it hard to ride a bike.", k: "wind", t: "O vento dificulta andar de bicicleta." },
    { q: "Children love to play in the ___.", k: "snow", t: "Crianças adoram brincar na neve." },
    { q: "The ___ covered the whole city.", k: "clouds", t: "As nuvens cobriram a cidade inteira." },
    { q: "We are having a very ___ summer.", k: "hot", t: "Estamos tendo um verão muito quente." },
    { q: "The ___ brought down many trees.", k: "storm", t: "A tempestade derrubou muitas árvores." },
    { q: "It's hard to breathe in ___ weather.", k: "humid", t: "É difícil respirar em tempo úmido." },
    { q: "The ___ weather is perfect for hiking.", k: "mild", t: "O tempo ameno é perfeito para caminhadas." },
    { q: "Plants don't grow well in ___ climates.", k: "dry", t: "As plantas não crescem bem em climas secos." },
    { q: "I feel ___ even indoors.", k: "chilly", t: "Sinto-me com frio mesmo dentro de casa." },
    { q: "The ___ night was full of stars.", k: "clear", t: "A noite clara estava cheia de estrelas." },
    { q: "We need to be prepared for heavy ___.", k: "rain", t: "Precisamos estar preparados para chuva forte." },
    { q: "The ___ picked up in the afternoon.", k: "wind", t: "O vento aumentou à tarde." },
    { q: "Is it going to ___ tomorrow?", k: "snow", t: "Vai nevar amanhã?" },
    { q: "I don't like ___ days, they are too depressing.", k: "cloudy", t: "Não gosto de dias nublados, são muito deprimentes." },
    { q: "He likes to swim in ___ water.", k: "hot", t: "Ele gosta de nadar em água quente." },
    { q: "A sudden ___ surprised everyone.", k: "storm", t: "Uma tempestade repentina surpreendeu a todos." },
    { q: "The air is thick and ___.", k: "humid", t: "O ar está denso e úmido." },
    { q: "We had a ___ winter this year.", k: "mild", t: "Tivemos um inverno ameno este ano." },
    { q: "The leaves are crisp in the ___ air.", k: "dry", t: "As folhas estão crocantes no ar seco." },
    { q: "It's a bit ___ for swimming.", k: "chilly", t: "Está um pouco frio para nadar." },
    { q: "The sky is ___ and blue.", k: "clear", t: "O céu está limpo e azul." },
    { q: "We stayed home because of the ___.", k: "rain", t: "Ficamos em casa por causa da chuva." },
    { q: "The ___ was strong enough to shake the house.", k: "wind", t: "O vento estava forte o suficiente para sacudir a casa." },
    { q: "Do you think it will ___ on Christmas?", k: "snow", t: "Você acha que vai nevar no Natal?" },
    { q: "The mountains are hidden by ___.", k: "clouds", t: "As montanhas estão escondidas pelas nuvens." },
    { q: "She loves to sunbathe on ___ days.", k: "hot", t: "Ela adora tomar sol em dias quentes." },
    { q: "The ___ damaged many buildings.", k: "storm", t: "A tempestade danificou muitos edifícios." },
    { q: "I can feel the ___ in the air.", k: "humidity", t: "Posso sentir a umidade no ar." },
    { q: "The temperature dropped, and it became ___.", k: "cold", t: "A temperatura caiu e ficou frio." },
    { q: "The fog made it a very ___ morning.", k: "misty", t: "O nevoeiro tornou a manhã muito enevoada." },
    { q: "It's an ideal day for a picnic, very ___.", k: "pleasant", t: "É um dia ideal para um piquenique, muito agradável." },
  ],
  aula4: [
    { q: "My ___ is the head of our family.", k: "father", t: "Meu pai é o chefe da nossa família." },
    { q: "My ___ always bakes delicious cakes.", k: "mother", t: "Minha mãe sempre assa bolos deliciosos." },
    { q: "I have one ___ and two sisters.", k: "brother", t: "Eu tenho um irmão e duas irmãs." },
    { q: "My elder ___ lives in another city.", k: "sister", t: "Minha irmã mais velha mora em outra cidade." },
    { q: "My ___ is my mother's sister.", k: "aunt", t: "Minha tia é a irmã da minha mãe." },
    { q: "My ___ is the child of my aunt and uncle.", k: "cousin", t: "Meu primo(a) é o(a) filho(a) da minha tia e tio." },
    { q: "My ___ are coming to visit next week.", k: "parents", t: "Meus pais vêm nos visitar na próxima semana." },
    { q: "My ___ is my father's brother.", k: "uncle", t: "Meu tio é o irmão do meu pai." },
    { q: "My ___ is my mother's father.", k: "grandfather", t: "Meu avô é o pai da minha mãe." },
    { q: "My ___ is my father's mother.", k: "grandmother", t: "Minha avó é a mãe do meu pai." },
    { q: "I love spending time with my ___.", k: "grandparents", t: "Adoro passar tempo com meus avós." },
    { q: "My ___ is my brother's son.", k: "nephew", t: "Meu sobrinho é o filho do meu irmão." },
    { q: "My ___ is my sister's daughter.", k: "niece", t: "Minha sobrinha é a filha da minha irmã." },
    { q: "My ___ is the son of my child.", k: "grandson", t: "Meu neto é o filho do meu filho." },
    { q: "My ___ is the daughter of my child.", k: "granddaughter", t: "Minha neta é a filha do meu filho." },
    { q: "My ___ are my children's children.", k: "grandchildren", t: "Meus netos são os filhos dos meus filhos." },
    { q: "My ___ is the husband of my daughter.", k: "son-in-law", t: "Meu genro é o marido da minha filha." },
    { q: "My ___ is the wife of my son.", k: "daughter-in-law", t: "Minha nora é a esposa do meu filho." },
    { q: "My ___ is my husband's or wife's mother.", k: "mother-in-law", t: "Minha sogra é a mãe do meu marido ou esposa." },
    { q: "My ___ is my husband's or wife's father.", k: "father-in-law", t: "Meu sogro é o pai do meu marido ou esposa." },
    { q: "My ___ is my husband's or wife's brother.", k: "brother-in-law", t: "Meu cunhado é o irmão do meu marido ou esposa." },
    { q: "My ___ is my husband's or wife's sister.", k: "sister-in-law", t: "Minha cunhada é a irmã do meu marido ou esposa." },
    { q: "We are a big ___ family.", k: "extended", t: "Somos uma grande família extensa." },
    { q: "He has a close-knit ___.", k: "family", t: "Ele tem uma família unida." },
    { q: "She is the youngest ___ in the family.", k: "child", t: "Ela é a criança mais nova da família." },
    { q: "They are celebrating their ___'s birthday.", k: "father's|fathers", t: "Eles estão celebrando o aniversário do pai deles." },
    { q: "My ___ teaches at a school.", k: "mother", t: "Minha mãe ensina em uma escola." },
    { q: "I share a room with my ___.", k: "brother", t: "Eu divido um quarto com meu irmão." },
    { q: "My ___ is getting married next month.", k: "sister", t: "Minha irmã vai se casar no próximo mês." },
    { q: "We visited our ___ in the countryside.", k: "aunt", t: "Visitamos nossa tia no campo." },
    { q: "My favorite ___ is always there for me.", k: "cousin", t: "Meu primo(a) favorito(a) está sempre lá para mim." },
    { q: "They rely on their ___ for support.", k: "parents", t: "Eles contam com o apoio de seus pais." },
    { q: "My ___ told us a funny story.", k: "uncle", t: "Meu tio nos contou uma história engraçada." },
    { q: "My ___ likes to tell stories about the past.", k: "grandfather", t: "Meu avô gosta de contar histórias sobre o passado." },
    { q: "My ___ is an amazing cook.", k: "grandmother", t: "Minha avó é uma cozinheira incrível." },
    { q: "The ___ enjoy playing with their toys.", k: "grandchildren", t: "Os netos gostam de brincar com seus brinquedos." },
    { q: "My ___ just started university.", k: "niece", t: "Minha sobrinha acabou de começar a universidade." },
    { q: "My ___ is a keen sportsman.", k: "nephew", t: "Meu sobrinho é um esportista entusiasmado." },
    { q: "He is very proud of his ___.", k: "son", t: "Ele tem muito orgulho de seu filho." },
    { q: "She is a loving ___.", k: "daughter", t: "Ela é uma filha amorosa." },
    { q: "We had a great time with our ___.", k: "relatives", t: "Nos divertimos muito com nossos parentes." },
    { q: "He is the oldest ___ in his family.", k: "sibling", t: "Ele é o irmão mais velho em sua família." },
    { q: "They are celebrating their ___ reunion.", k: "family", t: "Eles estão celebrando a reunião de sua família." },
    { q: "My ___ is a great role model.", k: "father", t: "Meu pai é um grande exemplo." },
    { q: "She is a wonderful ___ and friend.", k: "mother", t: "Ela é uma mãe e amiga maravilhosa." },
    { q: "My ___ always helps me with my homework.", k: "brother", t: "Meu irmão sempre me ajuda com meu dever de casa." },
    { q: "I like to go shopping with my ___.", k: "sister", t: "Eu gosto de fazer compras com minha irmã." },
    { q: "My ___ is like a second mother to me.", k: "aunt", t: "Minha tia é como uma segunda mãe para mim." },
    { q: "We always have fun with our ___.", k: "cousins", t: "Nós sempre nos divertimos com nossos primos." },
    { q: "They are grateful for their ___'s support.", k: "parents'|parents", t: "Eles são gratos pelo apoio de seus pais." },
  ],
  aula5: [
    { q: "___ book is this? It's mine.", k: "Whose", t: "De quem é este livro? É meu." },
    { q: "___ keys are these? They belong to John.", k: "Whose", t: "De quem são estas chaves? Elas pertencem ao John." },
    { q: "___ car is parked outside?", k: "Whose", t: "De quem é o carro estacionado lá fora?" },
    { q: "___ turn is it to play?", k: "Whose", t: "De quem é a vez de jogar?" },
    { q: "___ idea was it to go to the beach?", k: "Whose", t: "De quem foi a ideia de ir à praia?" },
    { q: "___ responsibility is this project?", k: "Whose", t: "De quem é a responsabilidade por este projeto?" },
    { q: "___ cat is that? It's very fluffy.", k: "Whose", t: "De quem é aquele gato? É muito fofo." },
    { q: "___ phone is ringing?", k: "Whose", t: "De quem é o telefone que está tocando?" },
    { q: "___ children are playing in the garden?", k: "Whose", t: "De quem são as crianças brincando no jardim?" },
    { q: "___ coat is this on the chair?", k: "Whose", t: "De quem é este casaco na cadeira?" },
    { q: "___ house are we going to tonight?", k: "Whose", t: "Na casa de quem vamos esta noite?" },
    { q: "___ decision was it to cancel the event?", k: "Whose", t: "De quem foi a decisão de cancelar o evento?" },
    { q: "___ opinion matters the most here?", k: "Whose", t: "A opinião de quem importa mais aqui?" },
    { q: "___ bag did you find?", k: "Whose", t: "A bolsa de quem você encontrou?" },
    { q: "___ voice is that?", k: "Whose", t: "De quem é aquela voz?" },
    { q: "___ shoes are these?", k: "Whose", t: "De quem são estes sapatos?" },
    { q: "___ advice should I follow?", k: "Whose", t: "O conselho de quem devo seguir?" },
    { q: "___ dog is barking?", k: "Whose", t: "De quem é o cachorro latindo?" },
    { q: "___ wallet was found?", k: "Whose", t: "A carteira de quem foi encontrada?" },
    { q: "___ turn is it to speak?", k: "Whose", t: "De quem é a vez de falar?" },
    { q: "___ project is this?", k: "Whose", t: "De quem é este projeto?" },
    { q: "___ umbrella is this?", k: "Whose", t: "De quem é este guarda-chuva?" },
    { q: "___ fault was it?", k: "Whose", t: "De quem foi a culpa?" },
    { q: "___ car is in the garage?", k: "Whose", t: "De quem é o carro na garagem?" },
    { q: "___ pen is this on the table?", k: "Whose", t: "De quem é esta caneta na mesa?" },
    { q: "___ parents are visiting?", k: "Whose", t: "Os pais de quem estão visitando?" },
    { q: "___ jacket is this?", k: "Whose", t: "De quem é esta jaqueta?" },
    { q: "___ book did you read?", k: "Whose", t: "O livro de quem você leu?" },
    { q: "___ idea was that?", k: "Whose", t: "De quem foi aquela ideia?" },
    { q: "___ bicycle is broken?", k: "Whose", t: "A bicicleta de quem está quebrada?" },
    { q: "___ problem is this?", k: "Whose", t: "De quem é este problema?" },
    { q: "___ hat is this?", k: "Whose", t: "De quem é este chapéu?" },
    { q: "___ dreams are these?", k: "Whose", t: "De quem são estes sonhos?" },
    { q: "___ backpack is this?", k: "Whose", t: "De quem é esta mochila?" },
    { q: "___ phone is charging?", k: "Whose", t: "De quem é o telefone que está carregando?" },
    { q: "___ tickets are these?", k: "Whose", t: "De quem são estes ingressos?" },
    { q: "___ house is that?", k: "Whose", t: "De quem é aquela casa?" },
    { q: "___ painting is this?", k: "Whose", t: "De quem é esta pintura?" },
    { q: "___ choice was that?", k: "Whose", t: "De quem foi aquela escolha?" },
    { q: "___ song is this?", k: "Whose", t: "De quem é esta música?" },
    { q: "___ bag is this?", k: "Whose", t: "De quem é esta bolsa?" },
    { q: "___ glasses are these?", k: "Whose", t: "De quem são estes óculos?" },
    { q: "___ dog is running around?", k: "Whose", t: "De quem é o cachorro correndo por aí?" },
    { q: "___ computer is this?", k: "Whose", t: "De quem é este computador?" },
    { q: "___ notes are these?", k: "Whose", t: "De quem são estas notas?" },
    { q: "___ sister is she?", k: "Whose", t: "Irmã de quem ela é?" },
    { q: "___ brother is he?", k: "Whose", t: "Irmão de quem ele é?" },
    { q: "___ kids are playing?", k: "Whose", t: "As crianças de quem estão brincando?" },
    { q: "___ coat is hanging here?", k: "Whose", t: "De quem é este casaco pendurado aqui?" },
    { q: "___ umbrella did you take?", k: "Whose", t: "O guarda-chuva de quem você pegou?" },
  ],
  aula6: [
    { q: "This is ___ book. (I)", k: "my", t: "Este é o meu livro." },
    { q: "That is ___ car. (you)", k: "your", t: "Aquele é o seu carro." },
    { q: "He gave me ___ phone number. (he)", k: "his", t: "Ele me deu o número de telefone dele." },
    { q: "She lost ___ keys. (she)", k: "her", t: "Ela perdeu as chaves dela." },
    { q: "The dog wagged ___ tail. (it)", k: "its", t: "O cachorro abanou o rabo dele." },
    { q: "We like ___ new house. (we)", k: "our", t: "Nós gostamos da nossa casa nova." },
    { q: "They brought ___ children. (they)", k: "their", t: "Eles trouxeram os filhos deles." },
    { q: "Is this ___ umbrella? (you)", k: "your", t: "Este é o seu guarda-chuva?" },
    { q: "This is ___ favorite song. (I)", k: "my", t: "Esta é a minha música favorita." },
    { q: "He showed us ___ new car. (he)", k: "his", t: "Ele nos mostrou o carro novo dele." },
    { q: "She introduced ___ friend. (she)", k: "her", t: "Ela apresentou a amiga dela." },
    { q: "The cat is eating ___ food. (it)", k: "its", t: "O gato está comendo a comida dele." },
    { q: "We finished ___ homework. (we)", k: "our", t: "Nós terminamos nossa lição de casa." },
    { q: "They are proud of ___ achievements. (they)", k: "their", t: "Eles estão orgulhosos de suas conquistas." },
    { q: "Can I borrow ___ pen? (you)", k: "your", t: "Posso pegar sua caneta emprestada?" },
    { q: "I washed ___ hands. (I)", k: "my", t: "Eu lavei minhas mãos." },
    { q: "He polished ___ shoes. (he)", k: "his", t: "Ele poliu os sapatos dele." },
    { q: "She brushed ___ hair. (she)", k: "her", t: "Ela escovou o cabelo dela." },
    { q: "The bird returned to ___ nest. (it)", k: "its", t: "O pássaro voltou para o ninho dele." },
    { q: "We packed ___ bags. (we)", k: "our", t: "Nós arrumamos nossas malas." },
    { q: "They parked ___ bikes. (they)", k: "their", t: "Eles estacionaram as bicicletas deles." },
    { q: "What is ___ name? (you)", k: "your", t: "Qual é o seu nome?" },
    { q: "I love ___ family. (I)", k: "my", t: "Eu amo minha família." },
    { q: "He loves ___ dog. (he)", k: "his", t: "Ele ama o cachorro dele." },
    { q: "She loves ___ cat. (she)", k: "her", t: "Ela ama o gato dela." },
    { q: "The company announced ___ new policy. (it)", k: "its", t: "A empresa anunciou a nova política dela." },
    { q: "We cleaned ___ room. (we)", k: "our", t: "Nós limpamos nosso quarto." },
    { q: "They sold ___ old car. (they)", k: "their", t: "Eles venderam o carro antigo deles." },
    { q: "Is this ___ decision? (you)", k: "your", t: "Esta é a sua decisão?" },
    { q: "I read ___ book. (I)", k: "my", t: "Eu li meu livro." },
    { q: "He fixed ___ computer. (he)", k: "his", t: "Ele consertou o computador dele." },
    { q: "She cooked ___ dinner. (she)", k: "her", t: "Ela cozinhou o jantar dela." },
    { q: "The tree lost ___ leaves. (it)", k: "its", t: "A árvore perdeu as folhas dela." },
    { q: "We celebrated ___ victory. (we)", k: "our", t: "Nós celebramos nossa vitória." },
    { q: "They shared ___ food. (they)", k: "their", t: "Eles compartilharam a comida deles." },
    { q: "Do you know ___ address? (you)", k: "your", t: "Você sabe o seu endereço?" },
    { q: "I finished ___ work. (I)", k: "my", t: "Eu terminei meu trabalho." },
    { q: "He bought ___ new jacket. (he)", k: "his", t: "Ele comprou a jaqueta nova dele." },
    { q: "She helped ___ mother. (she)", k: "her", t: "Ela ajudou a mãe dela." },
    { q: "The team won ___ game. (it)", k: "its", t: "O time venceu o jogo dele." },
    { q: "We visited ___ grandparents. (we)", k: "our", t: "Nós visitamos nossos avós." },
    { q: "They enjoy ___ vacation. (they)", k: "their", t: "Eles estão aproveitando as férias deles." },
    { q: "Where is ___ phone? (you)", k: "your", t: "Onde está o seu telefone?" },
    { q: "I forgot ___ wallet. (I)", k: "my", t: "Eu esqueci minha carteira." },
    { q: "He found ___ keys. (he)", k: "his", t: "Ele encontrou as chaves dele." },
    { q: "She introduced ___ husband. (she)", k: "her", t: "Ela apresentou o marido dela." },
    { q: "The baby cried for ___ toy. (it)", k: "its", t: "O bebê chorou pelo brinquedo dele." },
    { q: "We decorated ___ house. (we)", k: "our", t: "Nós decoramos nossa casa." },
    { q: "They cleaned ___ room. (they)", k: "their", t: "Eles limparam o quarto deles." },
    { q: "This is ___ problem. (I)", k: "my", t: "Este é o meu problema." },
  ],
  aula7: [
    { q: "___ is my pen. (near, singular)", k: "This", t: "Esta é minha caneta." },
    { q: "___ are my shoes. (near, plural)", k: "These", t: "Estes são meus sapatos." },
    { q: "___ is your car. (far, singular)", k: "That", t: "Aquele é o seu carro." },
    { q: "___ are their books. (far, plural)", k: "Those", t: "Aqueles são os livros deles." },
    { q: "Look at ___ bird in the sky. (far, singular)", k: "that", t: "Olhe aquele pássaro no céu." },
    { q: "Pass me ___ apples, please. (near, plural)", k: "these", t: "Me passe estas maçãs, por favor." },
    { q: "___ is an interesting idea. (near, singular)", k: "This", t: "Esta é uma ideia interessante." },
    { q: "___ cars are very fast. (far, plural)", k: "Those", t: "Aqueles carros são muito rápidos." },
    { q: "Can you see ___ mountains over there? (far, plural)", k: "those", t: "Você consegue ver aquelas montanhas lá?" },
    { q: "___ is a beautiful flower. (near, singular)", k: "This", t: "Esta é uma linda flor." },
    { q: "___ were the days! (far, plural)", k: "Those", t: "Aqueles eram os dias!" },
    { q: "I don't like ___ color. (near, singular)", k: "this", t: "Não gosto desta cor." },
    { q: "___ students are very clever. (near, plural)", k: "These", t: "Estes alunos são muito inteligentes." },
    { q: "Who is ___ man next to her? (far, singular)", k: "that", t: "Quem é aquele homem ao lado dela?" },
    { q: "___ are my favorite cookies. (near, plural)", k: "These", t: "Estes são meus biscoitos favoritos." },
    { q: "___ was a mistake. (far, singular)", k: "That", t: "Aquilo foi um erro." },
    { q: "Please take ___ documents to the office. (near, plural)", k: "these", t: "Por favor, leve estes documentos para o escritório." },
    { q: "Is ___ your jacket? (near, singular)", k: "this", t: "Esta é sua jaqueta?" },
    { q: "___ are not my keys. (near, plural)", k: "These", t: "Estas não são minhas chaves." },
    { q: "___ is a difficult question. (near, singular)", k: "This", t: "Esta é uma pergunta difícil." },
    { q: "___ children are making too much noise. (far, plural)", k: "Those", t: "Aquelas crianças estão fazendo muito barulho." },
    { q: "I saw ___ movie last night. (far, singular)", k: "that", t: "Eu assisti aquele filme ontem à noite." },
    { q: "___ is the best coffee. (near, singular)", k: "This", t: "Este é o melhor café." },
    { q: "___ are my friends. (near, plural)", k: "These", t: "Estes são meus amigos." },
    { q: "Do you remember ___ day? (far, singular)", k: "that", t: "Você se lembra daquele dia?" },
    { q: "___ books on the shelf are old. (far, plural)", k: "Those", t: "Aqueles livros na prateleira são antigos." },
    { q: "Look at ___ beautiful painting! (near, singular)", k: "this", t: "Olhe esta linda pintura!" },
    { q: "___ are my new shoes. (near, plural)", k: "These", t: "Estes são meus sapatos novos." },
    { q: "___ was a great concert. (far, singular)", k: "That", t: "Aquele foi um ótimo show." },
    { q: "___ flowers are for you. (near, plural)", k: "These", t: "Estas flores são para você." },
    { q: "I don't want ___ one. (near, singular)", k: "this", t: "Não quero este." },
    { q: "___ are interesting facts. (near, plural)", k: "These", t: "Estes são fatos interessantes." },
    { q: "___ is her brother. (far, singular)", k: "That", t: "Aquele é o irmão dela." },
    { q: "___ boys are playing football. (far, plural)", k: "Those", t: "Aqueles meninos estão jogando futebol." },
    { q: "Can I have ___ piece of cake? (near, singular)", k: "this", t: "Posso pegar este pedaço de bolo?" },
    { q: "___ are very useful tools. (near, plural)", k: "These", t: "Estas são ferramentas muito úteis." },
    { q: "___ was an amazing experience. (far, singular)", k: "That", t: "Aquela foi uma experiência incrível." },
    { q: "___ are expensive clothes. (far, plural)", k: "Those", t: "Aquelas são roupas caras." },
    { q: "Is ___ your bag? (near, singular)", k: "this", t: "Esta é sua bolsa?" },
    { q: "___ people are waiting for you. (far, plural)", k: "Those", t: "Aquelas pessoas estão esperando por você." },
    { q: "___ is not what I meant. (near, singular)", k: "This", t: "Isto não foi o que eu quis dizer." },
    { q: "___ are delicious apples. (near, plural)", k: "These", t: "Estas são maçãs deliciosas." },
    { q: "___ was a bad idea. (far, singular)", k: "That", t: "Aquela foi uma má ideia." },
    { q: "___ birds are singing. (near, plural)", k: "These", t: "Estes pássaros estão cantando." },
    { q: "Take ___ book with you. (near, singular)", k: "this", t: "Leve este livro com você." },
    { q: "___ are my parents. (near, plural)", k: "These", t: "Estes são meus pais." },
    { q: "___ is a beautiful day. (near, singular)", k: "This", t: "Este é um lindo dia." },
    { q: "___ are lovely flowers. (near, plural)", k: "These", t: "Estas são lindas flores." },
    { q: "___ was a long time ago. (far, singular)", k: "That", t: "Aquilo foi há muito tempo." },
    { q: "___ are good memories. (far, plural)", k: "Those", t: "Aquelas são boas lembranças." },
  ],
  aula8: [
    { q: "I ___ (visit) my grandparents last weekend.", k: "visited", t: "Eu visitei meus avós no último fim de semana." },
    { q: "She ___ (play) piano when she was a child.", k: "played", t: "Ela tocava piano quando era criança." },
    { q: "They ___ (go) to the cinema yesterday.", k: "went", t: "Eles foram ao cinema ontem." },
    { q: "He ___ (eat) pizza for dinner.", k: "ate", t: "Ele comeu pizza no jantar." },
    { q: "We ___ (see) a great movie last night.", k: "saw", t: "Nós vimos um ótimo filme ontem à noite." },
    { q: "She ___ (not / study) for the test.", k: "didn't study", t: "Ela não estudou para a prova." },
    { q: "___ you ___ (finish) your homework? (Did)", k: "Did finish", t: "Você terminou sua lição de casa?" },
    { q: "He ___ (write) a letter to his friend.", k: "wrote", t: "Ele escreveu uma carta para o amigo dele." },
    { q: "They ___ (arrive) late for the meeting.", k: "arrived", t: "Eles chegaram atrasados para a reunião." },
    { q: "I ___ (drink) a cup of tea this morning.", k: "drank", t: "Eu bebi uma xícara de chá esta manhã." },
    { q: "She ___ (not / come) to the party.", k: "didn't come", t: "Ela não veio à festa." },
    { q: "___ he ___ (call) you? (Did)", k: "Did call", t: "Ele te ligou?" },
    { q: "We ___ (have) a good time at the concert.", k: "had", t: "Nós nos divertimos no concerto." },
    { q: "He ___ (buy) a new car last month.", k: "bought", t: "Ele comprou um carro novo no mês passado." },
    { q: "They ___ (speak) English in class.", k: "spoke", t: "Eles falaram inglês na aula." },
    { q: "She ___ (begin) her journey early.", k: "began", t: "Ela começou sua jornada cedo." },
    { q: "I ___ (know) the answer yesterday.", k: "knew", t: "Eu sabia a resposta ontem." },
    { q: "He ___ (tell) me a secret.", k: "told", t: "Ele me contou um segredo." },
    { q: "They ___ (find) their lost dog.", k: "found", t: "Eles encontraram o cachorro perdido deles." },
    { q: "She ___ (forget) her umbrella.", k: "forgot", t: "Ela esqueceu o guarda-chuva dela." },
    { q: "We ___ (make) a cake for her birthday.", k: "made", t: "Nós fizemos um bolo para o aniversário dela." },
    { q: "He ___ (take) a lot of photos.", k: "took", t: "Ele tirou muitas fotos." },
    { q: "They ___ (give) him a present.", k: "gave", t: "Eles deram um presente a ele." },
    { q: "She ___ (run) in the marathon.", k: "ran", t: "Ela correu na maratona." },
    { q: "I ___ (understand) the lesson.", k: "understood", t: "Eu entendi a lição." },
    { q: "He ___ (sleep) for eight hours.", k: "slept", t: "Ele dormiu por oito horas." },
    { q: "They ___ (read) the whole book.", k: "read", t: "Eles leram o livro inteiro." },
    { q: "She ___ (sing) a beautiful song.", k: "sang", t: "Ela cantou uma linda música." },
    { q: "We ___ (build) a treehouse.", k: "built", t: "Nós construímos uma casa na árvore." },
    { q: "He ___ (drive) to work.", k: "drove", t: "Ele dirigiu para o trabalho." },
    { q: "They ___ (eat) all the food.", k: "ate", t: "Eles comeram toda a comida." },
    { q: "She ___ (see) her friend at the mall.", k: "saw", t: "Ela viu a amiga dela no shopping." },
    { q: "I ___ (write) an essay.", k: "wrote", t: "Eu escrevi uma redação." },
    { q: "He ___ (feel) sick yesterday.", k: "felt", t: "Ele se sentiu doente ontem." },
    { q: "They ___ (break) the window.", k: "broke", t: "Eles quebraram a janela." },
    { q: "She ___ (get) a new job.", k: "got", t: "Ela conseguiu um emprego novo." },
    { q: "We ___ (come) home late.", k: "came", t: "Nós chegamos em casa tarde." },
    { q: "He ___ (leave) his keys on the table.", k: "left", t: "Ele deixou as chaves dele na mesa." },
    { q: "They ___ (think) about their future.", k: "thought", t: "Eles pensaram sobre o futuro deles." },
    { q: "She ___ (lose) her wallet.", k: "lost", t: "Ela perdeu a carteira dela." },
    { q: "I ___ (meet) her last week.", k: "met", t: "Eu a encontrei na semana passada." },
    { q: "He ___ (sit) on the bench.", k: "sat", t: "Ele sentou no banco." },
    { q: "They ___ (stand) in line.", k: "stood", t: "Eles ficaram em pé na fila." },
    { q: "She ___ (teach) English for ten years.", k: "taught", t: "Ela ensinou inglês por dez anos." },
    { q: "We ___ (win) the game.", k: "won", t: "Nós vencemos o jogo." },
    { q: "He ___ (fly) to Paris.", k: "flew", t: "Ele voou para Paris." },
    { q: "They ___ (swim) in the ocean.", k: "swam", t: "Eles nadaram no oceano." },
    { q: "She ___ (hear) the news.", k: "heard", t: "Ela ouviu a notícia." },
    { q: "I ___ (spend) my vacation in Brazil.", k: "spent", t: "Eu passei minhas férias no Brasil." },
    { q: "He ___ (cut) the paper.", k: "cut", t: "Ele cortou o papel." },
  ],
  aula14: [
    { q: "She ___ (go) to school every day.", k: "goes", t: "Ela vai para a escola todos os dias." },
    { q: "They ___ (play) soccer on weekends.", k: "play", t: "Eles jogam futebol nos fins de semana." },
    { q: "He ___ (study) English in the evening.", k: "studies", t: "Ele estuda inglês à noite." },
    { q: "We ___ (live) in a big city.", k: "live", t: "Nós moramos em uma cidade grande." },
    { q: "I ___ (drink) coffee every morning.", k: "drink", t: "Eu bebo café todas as manhãs." },
    { q: "The sun ___ (rise) in the east.", k: "rises", t: "O sol nasce no leste." },
    { q: "Birds ___ (sing) in the morning.", k: "sing", t: "Os pássaros cantam de manhã." },
    { q: "He ___ (watch) TV after dinner.", k: "watches", t: "Ele assiste TV depois do jantar." },
    { q: "They ___ (have) a big house.", k: "have", t: "Eles têm uma casa grande." },
    { q: "She ___ (teach) mathematics.", k: "teaches", t: "Ela ensina matemática." },
    { q: "We ___ (eat) breakfast at 7 AM.", k: "eat", t: "Nós tomamos café da manhã às 7h." },
    { q: "My cat ___ (sleep) all day.", k: "sleeps", t: "Meu gato dorme o dia todo." },
    { q: "You ___ (work) very hard.", k: "work", t: "Você trabalha muito duro." },
    { q: "The train ___ (leave) at 8 o'clock.", k: "leaves", t: "O trem parte às 8 horas." },
    { q: "He never ___ (forget) his keys.", k: "forgets", t: "Ele nunca esquece as chaves dele." },
    { q: "They often ___ (visit) their grandparents.", k: "visit", t: "Eles frequentemente visitam seus avós." },
    { q: "She ___ (read) a book before bed.", k: "reads", t: "Ela lê um livro antes de dormir." },
    { q: "We ___ (speak) English at work.", k: "speak", t: "Nós falamos inglês no trabalho." },
    { q: "I ___ (listen) to music while working.", k: "listen", t: "Eu ouço música enquanto trabalho." },
    { q: "The dog ___ (bark) at strangers.", k: "barks", t: "O cachorro late para estranhos." },
    { q: "He always ___ (help) his friends.", k: "helps", t: "Ele sempre ajuda os amigos dele." },
    { q: "They ___ (go) to the gym daily.", k: "go", t: "Eles vão à academia diariamente." },
    { q: "She ___ (cook) dinner every night.", k: "cooks", t: "Ela cozinha o jantar todas as noites." },
    { q: "We ___ (travel) every summer.", k: "travel", t: "Nós viajamos todo verão." },
    { q: "I ___ (brush) my teeth twice a day.", k: "brush", t: "Eu escovo meus dentes duas vezes ao dia." },
    { q: "The baby ___ (cry) when he is hungry.", k: "cries", t: "O bebê chora quando está com fome." },
    { q: "He ___ (fix) cars for a living.", k: "fixes", t: "Ele conserta carros para viver." },
    { q: "They ___ (enjoy) spending time together.", k: "enjoy", t: "Eles gostam de passar tempo juntos." },
    { q: "She ___ (sing) beautifully.", k: "sing|sings", t: "Ela canta lindamente." },
    { q: "We ___ (watch) movies on Fridays.", k: "watch", t: "Nós assistimos filmes às sextas-feiras." },
    { q: "I ___ (write) emails every morning.", k: "write", t: "Eu escrevo e-mails todas as manhãs." },
    { q: "The store ___ (open) at 9 AM.", k: "opens", t: "A loja abre às 9h." },
    { q: "He ___ (finish) his work early.", k: "finishes", t: "Ele termina o trabalho dele cedo." },
    { q: "They ___ (believe) in ghosts.", k: "believe", t: "Eles acreditam em fantasmas." },
    { q: "She ___ (make) her own clothes.", k: "makes", t: "Ela faz as próprias roupas." },
    { q: "We ___ (study) hard for exams.", k: "study", t: "Nós estudamos muito para os exames." },
    { q: "I ___ (love) chocolate.", k: "love", t: "Eu amo chocolate." },
    { q: "The clock ___ (tick) loudly.", k: "ticks", t: "O relógio faz um tique-taque alto." },
    { q: "He ___ (drive) to work.", k: "drives", t: "Ele dirige para o trabalho." },
    { q: "They ___ (understand) the lesson.", k: "understand", t: "Eles entendem a lição." },
    { q: "She ___ (start) work at 8 AM.", k: "starts", t: "Ela começa a trabalhar às 8h." },
    { q: "We ___ (drink) a lot of water.", k: "drink", t: "Nós bebemos muita água." },
    { q: "I ___ (read) the newspaper daily.", k: "read", t: "Eu leio o jornal diariamente." },
    { q: "The wind ___ (blow) strongly.", k: "blows", t: "O vento sopra forte." },
    { q: "He ___ (play) the piano.", k: "plays", t: "Ele toca piano." },
    { q: "They ___ (walk) in the park.", k: "walk", t: "Eles caminham no parque." },
    { q: "She ___ (clean) her room.", k: "cleans", t: "Ela limpa o quarto dela." },
    { q: "We ___ (learn) new things.", k: "learn", t: "Nós aprendemos coisas novas." },
    { q: "I ___ (exercise) regularly.", k: "exercise", t: "Eu me exercito regularmente." },
    { q: "The factory ___ (produce) cars.", k: "produces", t: "A fábrica produz carros." },
  ],
  aula9: [
    { q: "I ___ (visit) my aunt tomorrow. (going to)", k: "am going to visit", t: "Vou visitar minha tia amanhã." },
    { q: "She ___ (buy) a new car next year. (will)", k: "will buy", t: "Ela comprará um carro novo no próximo ano." },
    { q: "They ___ (travel) to Japan next month. (going to)", k: "are going to travel", t: "Eles vão viajar para o Japão no próximo mês." },
    { q: "He ___ (not / come) to the party. (will)", k: "won't come", t: "Ele não virá à festa." },
    { q: "We ___ (eat) dinner at 7 PM. (going to)", k: "are going to eat", t: "Nós vamos jantar às 19h." },
    { q: "It ___ (rain) later. (will)", k: "will rain", t: "Vai chover mais tarde." },
    { q: "___ you ___ (help) me? (Will)", k: "Will help", t: "Você me ajudará?" },
    { q: "She ___ (start) a new job soon. (going to)", k: "is going to start", t: "Ela vai começar um novo emprego em breve." },
    { q: "They ___ (play) tennis this afternoon. (going to)", k: "are going to play", t: "Eles vão jogar tênis esta tarde." },
    { q: "I ___ (call) you back in 5 minutes. (will)", k: "will call", t: "Eu te ligo de volta em 5 minutos." },
    { q: "He ___ (not / forget) your birthday. (will)", k: "won't forget", t: "Ele não esquecerá seu aniversário." },
    { q: "We ___ (watch) a movie tonight. (going to)", k: "are going to watch", t: "Nós vamos assistir a um filme esta noite." },
    { q: "The plane ___ (land) in 10 minutes. (will)", k: "will land", t: "O avião vai pousar em 10 minutos." },
    { q: "She ___ (become) a doctor. (going to)", k: "is going to become", t: "Ela vai se tornar médica." },
    { q: "They ___ (build) a new house. (going to)", k: "are going to build", t: "Eles vão construir uma casa nova." },
    { q: "I ___ (open) the door for you. (will)", k: "will open", t: "Vou abrir a porta para você." },
    { q: "He ___ (not / pass) the exam. (will)", k: "won't pass", t: "Ele não passará no exame." },
    { q: "We ___ (have) a picnic this weekend. (going to)", k: "are going to have", t: "Nós vamos fazer um piquenique neste fim de semana." },
    { q: "It ___ (be) cold tomorrow. (will)", k: "will be", t: "Estará frio amanhã." },
    { q: "She ___ (meet) her friends later. (going to)", k: "is going to meet", t: "Ela vai encontrar as amigas dela mais tarde." },
    { q: "They ___ (learn) a new language. (going to)", k: "are going to learn", t: "Eles vão aprender uma nova língua." },
    { q: "I ___ (help) you with your bags. (will)", k: "will help", t: "Vou te ajudar com suas malas." },
    { q: "He ___ (not / win) the race. (will)", k: "won't win", t: "Ele não vai ganhar a corrida." },
    { q: "We ___ (cook) pasta tonight. (going to)", k: "are going to cook", t: "Nós vamos cozinhar macarrão hoje à noite." },
    { q: "The store ___ (close) at 9 PM. (will)", k: "will close", t: "A loja fechará às 21h." },
    { q: "She ___ (travel) around the world. (going to)", k: "is going to travel", t: "Ela vai viajar pelo mundo." },
    { q: "They ___ (start) their business soon. (going to)", k: "are going to start", t: "Eles vão começar o negócio deles em breve." },
    { q: "I ___ (send) you an email. (will)", k: "will send", t: "Eu vou te enviar um e-mail." },
    { q: "He ___ (not / finish) on time. (will)", k: "won't finish", t: "Ele não vai terminar a tempo." },
    { q: "We ___ (buy) a new sofa. (going to)", k: "are going to buy", t: "Nós vamos comprar um sofá novo." },
    { q: "It ___ (snow) next week. (will)", k: "will snow", t: "Vai nevar na próxima semana." },
    { q: "She ___ (read) that book. (going to)", k: "is going to read", t: "Ela vai ler aquele livro." },
    { q: "They ___ (move) to a new city. (going to)", k: "are going to move", t: "Eles vão se mudar para uma nova cidade." },
    { q: "I ___ (tell) you a secret. (will)", k: "will tell", t: "Vou te contar um segredo." },
    { q: "He ___ (not / like) the present. (will)", k: "won't like", t: "Ele não vai gostar do presente." },
    { q: "We ___ (celebrate) her birthday. (going to)", k: "are going to celebrate", t: "Nós vamos celebrar o aniversário dela." },
    { q: "The movie ___ (start) at 8 PM. (will)", k: "will start", t: "O filme vai começar às 20h." },
    { q: "She ___ (paint) her room. (going to)", k: "is going to paint", t: "Ela vai pintar o quarto dela." },
    { q: "They ___ (repair) the car. (going to)", k: "are going to repair", t: "Eles vão consertar o carro." },
    { q: "I ___ (bring) some snacks. (will)", k: "will bring", t: "Vou trazer alguns lanches." },
    { q: "He ___ (not / study) for the test. (will)", k: "won't study", t: "Ele não vai estudar para a prova." },
    { q: "We ___ (visit) the museum. (going to)", k: "are going to visit", t: "Nós vamos visitar o museu." },
    { q: "It ___ (be) sunny tomorrow. (will)", k: "will be", t: "Estará ensolarado amanhã." },
    { q: "She ___ (learn) to play guitar. (going to)", k: "is going to learn", t: "Ela vai aprender a tocar violão." },
    { q: "They ___ (clean) the house. (going to)", k: "are going to clean", t: "Eles vão limpar a casa." },
    { q: "I ___ (answer) your question. (will)", k: "will answer", t: "Vou responder sua pergunta." },
    { q: "He ___ (not / listen) to you. (will)", k: "won't listen", t: "Ele não vai te ouvir." },
    { q: "We ___ (watch) the football game. (going to)", k: "are going to watch", t: "Nós vamos assistir ao jogo de futebol." },
    { q: "The show ___ (end) soon. (will)", k: "will end", t: "O show vai acabar em breve." },
    { q: "She ___ (help) her brother. (going to)", k: "is going to help", t: "Ela vai ajudar o irmão dela." },
  ],
  aula10: [
    { q: "I ___ (study) English right now.", k: "am studying", t: "Estou estudando inglês agora." },
    { q: "She ___ (read) a book at the moment.", k: "is reading", t: "Ela está lendo um livro no momento." },
    { q: "They ___ (play) soccer in the park.", k: "are playing", t: "Eles estão jogando futebol no parque." },
    { q: "He ___ (not / work) today.", k: "isn't working", t: "Ele não está trabalhando hoje." },
    { q: "We ___ (eat) dinner together.", k: "are eating", t: "Nós estamos jantando juntos." },
    { q: "It ___ (rain) heavily outside.", k: "is raining", t: "Está chovendo muito lá fora." },
    { q: "___ you ___ (listen) to music? (Are)", k: "Are listening", t: "Você está ouvindo música?" },
    { q: "She ___ (write) an email.", k: "is writing", t: "Ela está escrevendo um e-mail." },
    { q: "They ___ (watch) TV.", k: "are watching", t: "Eles estão assistindo TV." },
    { q: "I ___ (wait) for the bus.", k: "am waiting", t: "Estou esperando pelo ônibus." },
    { q: "He ___ (talk) on the phone.", k: "is talking", t: "Ele está falando ao telefone." },
    { q: "We ___ (learn) a new language.", k: "are learning", t: "Nós estamos aprendendo uma nova língua." },
    { q: "The birds ___ (sing) beautifully.", k: "are singing", t: "Os pássaros estão cantando lindamente." },
    { q: "She ___ (cook) lunch.", k: "is cooking", t: "Ela está cozinhando o almoço." },
    { q: "They ___ (dance) at the party.", k: "are dancing", t: "Eles estão dançando na festa." },
    { q: "I ___ (clean) my room.", k: "am cleaning", t: "Estou limpando meu quarto." },
    { q: "He ___ (sleep) in his bed.", k: "is sleeping", t: "Ele está dormindo na cama dele." },
    { q: "We ___ (have) a good time.", k: "are having", t: "Nós estamos nos divertindo." },
    { q: "The dog ___ (bark) at the mailman.", k: "is barking", t: "O cachorro está latindo para o carteiro." },
    { q: "She ___ (run) in the park.", k: "is running", t: "Ela está correndo no parque." },
    { q: "They ___ (build) a new house.", k: "are building", t: "Eles estão construindo uma casa nova." },
    { q: "I ___ (drink) water.", k: "am drinking", t: "Estou bebendo água." },
    { q: "He ___ (draw) a picture.", k: "is drawing", t: "Ele está desenhando um quadro." },
    { q: "We ___ (walk) to school.", k: "are walking", t: "Nós estamos caminhando para a escola." },
    { q: "The baby ___ (cry).", k: "is crying", t: "O bebê está chorando." },
    { q: "She ___ (help) her mother.", k: "is helping", t: "Ela está ajudando a mãe dela." },
    { q: "They ___ (shop) for groceries.", k: "are shopping", t: "Eles estão fazendo compras." },
    { q: "I ___ (listen) to the radio.", k: "am listening", t: "Estou ouvindo rádio." },
    { q: "He ___ (play) guitar.", k: "is playing", t: "Ele está tocando violão." },
    { q: "We ___ (study) for our exams.", k: "are studying", t: "Nós estamos estudando para nossos exames." },
    { q: "The sun ___ (shine).", k: "is shining", t: "O sol está brilhando." },
    { q: "She ___ (eat) an apple.", k: "is eating", t: "Ela está comendo uma maçã." },
    { q: "They ___ (swim) in the pool.", k: "are swimming", t: "Eles estão nadando na piscina." },
    { q: "I ___ (talk) to my friend.", k: "am talking", t: "Estou falando com meu amigo." },
    { q: "He ___ (write) a letter.", k: "is writing", t: "Ele está escrevendo uma carta." },
    { q: "We ___ (go) to the cinema.", k: "are going", t: "Nós estamos indo ao cinema." },
    { q: "The chef ___ (cook) a delicious meal.", k: "is cooking", t: "O chef está cozinhando uma refeição deliciosa." },
    { q: "She ___ (sing) a song.", k: "is singing", t: "Ela está cantando uma música." },
    { q: "They ___ (work) on a project.", k: "are working", t: "Eles estão trabalhando em um projeto." },
    { q: "I ___ (sit) on the chair.", k: "am sitting", t: "Estou sentado na cadeira." },
    { q: "He ___ (read) the newspaper.", k: "is reading", t: "Ele está lendo o jornal." },
    { q: "We ___ (travel) around the world.", k: "are traveling", t: "Nós estamos viajando pelo mundo." },
    { q: "The kids ___ (play) with toys.", k: "are playing", t: "As crianças estão brincando com brinquedos." },
    { q: "She ___ (take) a picture.", k: "is taking", t: "Ela está tirando uma foto." },
    { q: "They ___ (wait) for you.", k: "are waiting", t: "Eles estão esperando por você." },
    { q: "I ___ (think) about my vacation.", k: "am thinking", t: "Estou pensando nas minhas férias." },
    { q: "He ___ (clean) the kitchen.", k: "is cleaning", t: "Ele está limpando a cozinha." },
    { q: "We ___ (plan) our trip.", k: "are planning", t: "Nós estamos planejando nossa viagem." },
    { q: "The wind ___ (blow) gently.", k: "is blowing", t: "O vento está soprando suavemente." },
    { q: "She ___ (watch) a documentary.", k: "is watching", t: "Ela está assistindo a um documentário." },
  ],
  aula11: [
    { q: "I ___ (read) a book when you called.", k: "was reading", t: "Eu estava lendo um livro quando você ligou." },
    { q: "She ___ (sleep) when the phone rang.", k: "was sleeping", t: "Ela estava dormindo quando o telefone tocou." },
    { q: "They ___ (play) outside all afternoon.", k: "were playing", t: "Eles estavam brincando lá fora a tarde toda." },
    { q: "He ___ (not / listen) to me.", k: "wasn't listening", t: "Ele não estava me ouvindo." },
    { q: "We ___ (eat) dinner at 8 PM yesterday.", k: "were eating", t: "Nós estávamos jantando às 20h ontem." },
    { q: "It ___ (rain) when I woke up.", k: "was raining", t: "Estava chovendo quando acordei." },
    { q: "___ you ___ (watch) TV? (Were)", k: "Were watching", t: "Você estava assistindo TV?" },
    { q: "She ___ (sing) a song while she was cooking.", k: "was singing", t: "Ela estava cantando uma música enquanto cozinhava." },
    { q: "They ___ (study) for their exam.", k: "were studying", t: "Eles estavam estudando para o exame deles." },
    { q: "I ___ (wait) for him at the cafe.", k: "was waiting", t: "Eu estava esperando por ele no café." },
    { q: "He ___ (work) on his computer.", k: "was working", t: "Ele estava trabalhando no computador dele." },
    { q: "We ___ (talk) about our plans.", k: "were talking", t: "Nós estávamos conversando sobre nossos planos." },
    { q: "The children ___ (run) in the garden.", k: "were running", t: "As crianças estavam correndo no jardim." },
    { q: "She ___ (clean) her room all morning.", k: "was cleaning", t: "Ela estava limpando o quarto dela a manhã toda." },
    { q: "They ___ (dance) when the music stopped.", k: "were dancing", t: "Eles estavam dançando quando a música parou." },
    { q: "I ___ (cook) when the electricity went out.", k: "was cooking", t: "Eu estava cozinhando quando a energia acabou." },
    { q: "He ___ (drive) to work when he saw the accident.", k: "was driving", t: "Ele estava dirigindo para o trabalho quando viu o acidente." },
    { q: "We ___ (listen) to the radio.", k: "were listening", t: "Nós estávamos ouvindo rádio." },
    { q: "The dog ___ (bark) loudly.", k: "was barking", t: "O cachorro estava latindo alto." },
    { q: "She ___ (write) an article for the newspaper.", k: "was writing", t: "Ela estava escrevendo um artigo para o jornal." },
    { q: "They ___ (build) a sandcastle on the beach.", k: "were building", t: "Eles estavam construindo um castelo de areia na praia." },
    { q: "I ___ (drink) tea when she arrived.", k: "was drinking", t: "Eu estava tomando chá quando ela chegou." },
    { q: "He ___ (draw) a landscape.", k: "was drawing", t: "Ele estava desenhando uma paisagem." },
    { q: "We ___ (walk) in the park when it started to rain.", k: "were walking", t: "Nós estávamos caminhando no parque quando começou a chover." },
    { q: "The baby ___ (sleep) peacefully.", k: "was sleeping", t: "O bebê estava dormindo tranquilamente." },
    { q: "She ___ (help) her neighbor.", k: "was helping", t: "Ela estava ajudando o vizinho dela." },
    { q: "They ___ (shop) at the mall.", k: "were shopping", t: "Eles estavam fazendo compras no shopping." },
    { q: "I ___ (watch) a movie on Netflix.", k: "was watching", t: "Eu estava assistindo a um filme na Netflix." },
    { q: "He ___ (play) video games.", k: "was playing", t: "Ele estava jogando videogame." },
    { q: "We ___ (have) a party.", k: "were having", t: "Nós estávamos fazendo uma festa." },
    { q: "The sun ___ (set) beautifully.", k: "was setting", t: "O sol estava se pondo lindamente." },
    { q: "She ___ (eat) breakfast.", k: "was eating", t: "Ela estava tomando café da manhã." },
    { q: "They ___ (swim) in the lake.", k: "were swimming", t: "Eles estavam nadando no lago." },
    { q: "I ___ (talk) on the phone.", k: "was talking", t: "Eu estava falando ao telefone." },
    { q: "He ___ (read) an interesting article.", k: "was reading", t: "Ele estava lendo um artigo interessante." },
    { q: "We ___ (go) to the concert.", k: "were going", t: "Nós estávamos indo ao concerto." },
    { q: "The wind ___ (blow) strongly.", k: "was blowing", t: "O vento estava soprando forte." },
    { q: "She ___ (do) her homework.", k: "was doing", t: "Ela estava fazendo a lição de casa dela." },
    { q: "They ___ (work) on their project.", k: "were working", t: "Eles estavam trabalhando no projeto deles." },
    { q: "I ___ (sit) in the garden.", k: "was sitting", t: "Eu estava sentado no jardim." },
    { q: "He ___ (listen) to music.", k: "was listening", t: "Ele estava ouvindo música." },
    { q: "We ___ (plan) our vacation.", k: "were planning", t: "Nós estávamos planejando nossas férias." },
    { q: "The students ___ (take) a test.", k: "were taking", t: "Os alunos estavam fazendo uma prova." },
    { q: "She ___ (prepare) for the presentation.", k: "was preparing", t: "Ela estava se preparando para a apresentação." },
    { q: "They ___ (discuss) the new policy.", k: "were discussing", t: "Eles estavam discutindo a nova política." },
    { q: "I ___ (think) about you.", k: "was thinking", t: "Eu estava pensando em você." },
    { q: "He ___ (repair) his bicycle.", k: "was repairing", t: "Ele estava consertando a bicicleta dele." },
    { q: "We ___ (wait) for the results.", k: "were waiting", t: "Nós estávamos esperando pelos resultados." },
    { q: "The teacher ___ (explain) the lesson.", k: "was explaining", t: "A professora estava explicando a lição." },
    { q: "She ___ (look) for her keys.", k: "was looking", t: "Ela estava procurando pelas chaves dela." },
  ],
  aula12: [
    { q: "She gave the book to ___ (I).", k: "me", t: "Ela me deu o livro." },
    { q: "I saw ___ at the party. (you)", k: "you", t: "Eu te vi na festa." },
    { q: "We invited ___ to dinner. (he)", k: "him", t: "Nós o convidamos para jantar." },
    { q: "He talked to ___ about the problem. (she)", k: "her", t: "Ele falou com ela sobre o problema." },
    { q: "The dog followed ___. (it)", k: "it", t: "O cachorro o seguiu." },
    { q: "She helped ___ with our homework. (we)", k: "us", t: "Ela nos ajudou com nossa lição de casa." },
    { q: "I called ___ yesterday. (they)", k: "them", t: "Eu liguei para eles ontem." },
    { q: "Can you pass ___ the salt? (I)", k: "me", t: "Você pode me passar o sal?" },
    { q: "The teacher asked ___ a question. (you)", k: "you", t: "O professor te fez uma pergunta." },
    { q: "I sent ___ an email. (he)", k: "him", t: "Eu enviei um e-mail para ele." },
    { q: "He gave ___ a present. (she)", k: "her", t: "Ele deu um presente para ela." },
    { q: "The cat looked at ___. (it)", k: "it", t: "O gato olhou para ele." },
    { q: "She brought flowers for ___. (we)", k: "us", t: "Ela trouxe flores para nós." },
    { q: "We visited ___ last summer. (they)", k: "them", t: "Nós os visitamos no verão passado." },
    { q: "Tell ___ the truth. (I)", k: "me", t: "Me diga a verdade." },
    { q: "I can help ___ with that. (you)", k: "you", t: "Eu posso te ajudar com isso." },
    { q: "She loves ___. (he)", k: "him", t: "Ela o ama." },
    { q: "He misses ___. (she)", k: "her", t: "Ele sente falta dela." },
    { q: "Don't touch ___. (it)", k: "it", t: "Não toque nisso." },
    { q: "He told ___ a secret. (we)", k: "us", t: "Ele nos contou um segredo." },
    { q: "They saw ___ at the concert. (I)", k: "me", t: "Eles me viram no concerto." },
    { q: "I need to talk to ___. (you)", k: "you", t: "Preciso falar com você." },
    { q: "Give ___ the money. (he)", k: "him", t: "Dê o dinheiro a ele." },
    { q: "I saw ___ at the store. (she)", k: "her", t: "Eu a vi na loja." },
    { q: "He kicked ___. (it - ball)", k: "it", t: "Ele o chutou." },
    { q: "She cooked dinner for ___. (we)", k: "us", t: "Ela cozinhou o jantar para nós." },
    { q: "We played with ___ in the park. (they)", k: "them", t: "Nós brincamos com eles no parque." },
    { q: "Can you hear ___? (I)", k: "me", t: "Você consegue me ouvir?" },
    { q: "I believe ___. (you)", k: "you", t: "Eu acredito em você." },
    { q: "She called ___. (he)", k: "him", t: "Ela o ligou." },
    { q: "He thanked ___. (she)", k: "her", t: "Ele a agradeceu." },
    { q: "The dog licked ___. (it)", k: "it", t: "O cachorro o lambeu." },
    { q: "They joined ___. (we)", k: "us", t: "Eles se juntaram a nós." },
    { q: "I followed ___. (they)", k: "them", t: "Eu os segui." },
    { q: "Please explain ___ again. (I)", k: "me", t: "Por favor, me explique novamente." },
    { q: "Are you talking to ___? (you)", k: "me", t: "Você está falando comigo?" },
    { q: "She waved at ___. (he)", k: "him", t: "Ela acenou para ele." },
    { q: "He looked at ___. (she)", k: "her", t: "Ele olhou para ela." },
    { q: "The bird watched ___. (it)", k: "it", t: "O pássaro o observou." },
    { q: "They offered ___ a ride. (we)", k: "us", t: "Eles nos ofereceram uma carona." },
    { q: "We waited for ___. (they)", k: "them", t: "Nós esperamos por eles." },
    { q: "I understood ___. (you)", k: "you", t: "Eu te entendi." },
    { q: "She spoke to ___. (he)", k: "him", t: "Ela falou com ele." },
    { q: "He listened to ___. (she)", k: "her", t: "Ele a ouviu." },
    { q: "The car hit ___. (it - tree)", k: "it", t: "O carro o atingiu." },
    { q: "They sent ___ a postcard. (we)", k: "us", t: "Eles nos enviaram um cartão postal." },
    { q: "I helped ___. (they)", k: "them", t: "Eu os ajudei." },
    { q: "Can you see ___? (I)", k: "me", t: "Você consegue me ver?" },
    { q: "I like ___. (you)", k: "you", t: "Eu gosto de você." },
    { q: "She likes ___. (he)", k: "him", t: "Ela gosta dele." },
  ],
  aula13: [
    { q: "The movie was ___ good.", k: "very", t: "O filme foi muito bom." },
    { q: "I am ___ tired today.", k: "really", t: "Estou realmente cansado hoje." },
    { q: "It's ___ hot outside.", k: "so", t: "Está tão quente lá fora." },
    { q: "This coffee is ___ hot to drink.", k: "too", t: "Este café está muito quente para beber." },
    { q: "She is ___ beautiful.", k: "very", t: "Ela é muito bonita." },
    { q: "He is ___ intelligent.", k: "really", t: "Ele é realmente inteligente." },
    { q: "The test was ___ difficult.", k: "so", t: "A prova foi tão difícil." },
    { q: "The music is ___ loud.", k: "too", t: "A música está muito alta." },
    { q: "I am ___ happy to see you.", k: "very", t: "Estou muito feliz em te ver." },
    { q: "It was ___ cold yesterday.", k: "really", t: "Estava realmente frio ontem." },
    { q: "The book was ___ interesting.", k: "so", t: "O livro foi tão interessante." },
    { q: "This bag is ___ heavy for me.", k: "too", t: "Esta bolsa é muito pesada para mim." },
    { q: "She is a ___ good student.", k: "very", t: "Ela é uma aluna muito boa." },
    { q: "He drives ___ fast.", k: "really", t: "Ele dirige muito rápido." },
    { q: "The food was ___ delicious.", k: "so", t: "A comida estava tão deliciosa." },
    { q: "It's ___ late to go out.", k: "too", t: "É muito tarde para sair." },
    { q: "I feel ___ relaxed after the massage.", k: "very", t: "Eu me sinto muito relaxado(a) depois da massagem." },
    { q: "The news was ___ shocking.", k: "really", t: "A notícia foi realmente chocante." },
    { q: "You are ___ kind.", k: "so", t: "Você é tão gentil." },
    { q: "He is ___ young to drive.", k: "too", t: "Ele é muito jovem para dirigir." },
    { q: "The view is ___ amazing.", k: "very", t: "A vista é muito incrível." },
    { q: "She is ___ talented.", k: "really", t: "Ela é realmente talentosa." },
    { q: "I am ___ sorry.", k: "so", t: "Sinto muito." },
    { q: "It's ___ dark in here.", k: "too", t: "Está muito escuro aqui." },
    { q: "This is a ___ important meeting.", k: "very", t: "Esta é uma reunião muito importante." },
    { q: "He is ___ strong.", k: "really", t: "Ele é realmente forte." },
    { q: "The movie was ___ sad.", k: "so", t: "O filme foi tão triste." },
    { q: "This puzzle is ___ difficult.", k: "too", t: "Este quebra-cabeça é muito difícil." },
    { q: "She is ___ excited about her trip.", k: "very", t: "Ela está muito animada com a viagem dela." },
    { q: "The concert was ___ good.", k: "really", t: "O concerto foi realmente bom." },
    { q: "It's ___ beautiful outside.", k: "so", t: "Está tão bonito lá fora." },
    { q: "He talks ___ much.", k: "too", t: "Ele fala demais." },
    { q: "I am ___ grateful for your help.", k: "very", t: "Sou muito grato(a) pela sua ajuda." },
    { q: "The performance was ___ impressive.", k: "really", t: "A apresentação foi realmente impressionante." },
    { q: "You are ___ sweet.", k: "so", t: "Você é tão doce." },
    { q: "She is ___ busy to talk.", k: "too", t: "Ela está muito ocupada para falar." },
    { q: "This is ___ delicious.", k: "very", t: "Isto é muito delicioso." },
    { q: "The car is ___ expensive.", k: "really", t: "O carro é realmente caro." },
    { q: "I am ___ happy for you.", k: "so", t: "Estou tão feliz por você." },
    { q: "It's ___ risky.", k: "too", t: "É muito arriscado." },
    { q: "She is ___ intelligent.", k: "very", t: "Ela é muito inteligente." },
    { q: "He is ___ funny.", k: "really", t: "Ele é realmente engraçado." },
    { q: "The news was ___ exciting.", k: "so", t: "A notícia foi tão emocionante." },
    { q: "It's ___ early to leave.", k: "too", t: "É muito cedo para sair." },
    { q: "I am ___ disappointed.", k: "very", t: "Estou muito desapontado(a)." },
    { q: "She is ___ shy.", k: "really", t: "Ela é realmente tímida." },
    { q: "You are ___ amazing.", k: "so", t: "Você é tão incrível." },
    { q: "He is ___ sensitive.", k: "too", t: "Ele é muito sensível." },
    { q: "This is ___ interesting.", k: "very", t: "Isto é muito interessante." },
    { q: "The weather is ___ bad.", k: "really", t: "O tempo está muito ruim." },
  ],
  aula15: [
    { q: "___ is your name?", k: "What", t: "Qual é o seu nome?" },
    { q: "___ do you live?", k: "Where", t: "Onde você mora?" },
    { q: "___ is your favorite color?", k: "What", t: "Qual é a sua cor favorita?" },
    { q: "___ do you go to bed?", k: "When", t: "Quando você vai para a cama?" },
    { q: "___ is he? He is my brother.", k: "Who", t: "Quem é ele? Ele é meu irmão." },
    { q: "___ do you want to eat?", k: "What", t: "O que você quer comer?" },
    { q: "___ is your birthday?", k: "When", t: "Quando é o seu aniversário?" },
    { q: "___ is the capital of France?", k: "What", t: "Qual é a capital da França?" },
    { q: "___ did you buy that?", k: "Where", t: "Onde você comprou isso?" },
    { q: "___ is your teacher?", k: "Who", t: "Quem é seu professor?" },
    { q: "___ are you crying?", k: "Why", t: "Por que você está chorando?" },
    { q: "___ old are you?", k: "How", t: "Quantos anos você tem?" },
    { q: "___ time is it?", k: "What", t: "Que horas são?" },
    { q: "___ did you arrive?", k: "When", t: "Quando você chegou?" },
    { q: "___ is your favorite animal?", k: "What", t: "Qual é o seu animal favorito?" },
    { q: "___ are you going?", k: "Where", t: "Onde você vai?" },
    { q: "___ is she? She is my mother.", k: "Who", t: "Quem é ela? Ela é minha mãe." },
    { q: "___ do you like it?", k: "Why", t: "Por que você gosta disso?" },
    { q: "___ do you go to school?", k: "How", t: "Como você vai para a escola?" },
    { q: "___ is your favorite food?", k: "What", t: "Qual é a sua comida favorita?" },
    { q: "___ did you meet him?", k: "When", t: "Quando você o conheceu?" },
    { q: "___ is your address?", k: "Where", t: "Qual é o seu endereço?" },
    { q: "___ is your best friend?", k: "Who", t: "Quem é o seu melhor amigo?" },
    { q: "___ are you laughing?", k: "Why", t: "Por que você está rindo?" },
    { q: "___ many books do you have?", k: "How", t: "Quantos livros você tem?" },
    { q: "___ kind of music do you listen to?", k: "What", t: "Que tipo de música você ouve?" },
    { q: "___ did you learn English?", k: "When", t: "Quando você aprendeu inglês?" },
    { q: "___ is the nearest bus stop?", k: "Where", t: "Onde fica o ponto de ônibus mais próximo?" },
    { q: "___ broke the window?", k: "Who", t: "Quem quebrou a janela?" },
    { q: "___ are you sad?", k: "Why", t: "Por que você está triste?" },
    { q: "___ do you feel?", k: "How", t: "Como você se sente?" },
    { q: "___ subject do you like the most?", k: "What", t: "Qual matéria você mais gosta?" },
    { q: "___ did the accident happen?", k: "When", t: "Quando o acidente aconteceu?" },
    { q: "___ is your car?", k: "Where", t: "Onde está seu carro?" },
    { q: "___ is the new student?", k: "Who", t: "Quem é o novo aluno?" },
    { q: "___ did you do that?", k: "Why", t: "Por que você fez isso?" },
    { q: "___ much does it cost?", k: "How", t: "Quanto custa?" },
    { q: "___ movie did you watch?", k: "What", t: "Que filme você assistiu?" },
    { q: "___ did you come here?", k: "When", t: "Quando você veio aqui?" },
    { q: "___ is your workplace?", k: "Where", t: "Onde é seu local de trabalho?" },
    { q: "___ is your favorite actor?", k: "Who", t: "Quem é seu ator favorito?" },
    { q: "___ are you so happy?", k: "Why", t: "Por que você está tão feliz?" },
    { q: "___ do you spell your name?", k: "How", t: "Como se soletra seu nome?" },
    { q: "___ sports do you play?", k: "What", t: "Que esportes você pratica?" },
    { q: "___ did you last see him?", k: "When", t: "Quando você o viu pela última vez?" },
    { q: "___ is your school?", k: "Where", t: "Onde é sua escola?" },
    { q: "___ is calling me?", k: "Who", t: "Quem está me ligando?" },
    { q: "___ did you choose this?", k: "Why", t: "Por que você escolheu isso?" },
    { q: "___ was the weather like?", k: "How", t: "Como estava o tempo?" },
    { q: "___ is your favorite hobby?", k: "What", t: "Qual é o seu hobby favorito?" },
  ],
  aula16: [
    { q: "I need to ___ my old clothes. (donate/throw away)", k: "give up", t: "Preciso doar/jogar fora minhas roupas velhas." },
    { q: "Can you ___ the music? It's too loud. (reduce volume)", k: "turn down", t: "Você pode abaixar o volume da música? Está muito alto." },
    { q: "She decided to ___ smoking. (stop)", k: "give up", t: "Ela decidiu parar de fumar." },
    { q: "We need to ___ early tomorrow. (start a journey)", k: "set off", t: "Precisamos partir cedo amanhã." },
    { q: "He will ___ the problem. (investigate)", k: "look into", t: "Ele vai investigar o problema." },
    { q: "Don't forget to ___ the lights when you leave. (extinguish)", k: "turn off", t: "Não se esqueça de apagar as luzes quando sair." },
    { q: "I ___ my keys this morning. (find by chance)", k: "came across", t: "Eu encontrei minhas chaves esta manhã por acaso." },
    { q: "She always ___ her promises. (fulfill)", k: "carries out", t: "Ela sempre cumpre suas promessas." },
    { q: "They ___ a new plan. (invent/create)", k: "came up with", t: "Eles inventaram um novo plano." },
    { q: "He needs to ___ his grades. (improve)", k: "bring up", t: "Ele precisa melhorar suas notas." },
    { q: "We need to ___ our differences. (resolve)", k: "work out", t: "Precisamos resolver nossas diferenças." },
    { q: "She decided to ___ running. (start a hobby)", k: "take up", t: "Ela decidiu começar a correr." },
    { q: "Can you ___ what he said? (understand)", k: "make out", t: "Você consegue entender o que ele disse?" },
    { q: "I will ___ you at the airport. (collect)", k: "pick up", t: "Eu vou te buscar no aeroporto." },
    { q: "They ___ because of the bad weather. (cancel)", k: "called off", t: "Eles cancelaram por causa do mau tempo." },
    { q: "He ___ his old friend at the mall. (meet by chance)", k: "ran into", t: "Ele encontrou seu velho amigo no shopping por acaso." },
    { q: "She needs to ___ her children. (raise)", k: "bring up", t: "Ela precisa criar seus filhos." },
    { q: "We will ___ the celebration until next week. (postpone)", k: "put off", t: "Nós vamos adiar a celebração para a próxima semana." },
    { q: "The police are ___ the case. (investigating)", k: "looking into", t: "A polícia está investigando o caso." },
    { q: "Please ___ the form. (complete)", k: "fill out", t: "Por favor, preencha o formulário." },
    { q: "He wants to ___ a new business. (establish)", k: "set up", t: "Ele quer estabelecer um novo negócio." },
    { q: "She likes to ___ new challenges. (accept)", k: "take on", t: "Ela gosta de aceitar novos desafios." },
    { q: "They need to ___ the rules. (obey)", k: "abide by", t: "Eles precisam obedecer às regras." },
    { q: "I will ___ my promise. (keep)", k: "carry out", t: "Eu vou cumprir minha promessa." },
    { q: "He had to ___ his trip. (cancel)", k: "call off", t: "Ele teve que cancelar sua viagem." },
    { q: "She ___ an old photograph. (discover by chance)", k: "came across", t: "Ela encontrou uma fotografia antiga por acaso." },
    { q: "We need to ___ a solution. (find)", k: "come up with", t: "Precisamos encontrar uma solução." },
    { q: "Can you ___ the TV? (increase volume)", k: "turn up", t: "Você pode aumentar o volume da TV?" },
    { q: "Don't ___ on your dreams. (abandon)", k: "give up", t: "Não desista dos seus sonhos." },
    { q: "They ___ their new project next month. (begin)", k: "kick off", t: "Eles iniciarão o novo projeto deles no próximo mês." },
    { q: "He always ___ his word. (keep)", k: "stands by", t: "Ele sempre cumpre sua palavra." },
    { q: "She needs to ___ after her younger sister. (take care of)", k: "look after", t: "Ela precisa cuidar da irmã mais nova dela." },
    { q: "We need to ___ the issue. (discuss)", k: "talk over", t: "Precisamos discutir a questão." },
    { q: "I will ___ the application form. (submit)", k: "hand in", t: "Eu vou entregar o formulário de inscrição." },
    { q: "He had to ___ a lot of challenges. (face)", k: "deal with", t: "Ele teve que lidar com muitos desafios." },
    { q: "She needs to ___ her past. (forget)", k: "get over", t: "Ela precisa superar o passado dela." },
    { q: "They decided to ___ early. (leave)", k: "set off", t: "Eles decidiram partir cedo." },
    { q: "I will ___ you later. (call)", k: "call back", t: "Eu te ligo de volta mais tarde." },
    { q: "He had to ___ to his parents' demands. (yield)", k: "give in", t: "Ele teve que ceder às exigências de seus pais." },
    { q: "She will ___ her best to succeed. (try)", k: "do her best|do her best", t: "Ela fará o seu melhor para ter sucesso." },
    { q: "We need to ___ the report by Friday. (complete)", k: "hand in", t: "Precisamos entregar o relatório até sexta-feira." },
    { q: "He will ___ the problem to his manager. (explain)", k: "point out", t: "Ele vai apontar o problema para o gerente dele." },
    { q: "She likes to ___ new ideas. (experiment with)", k: "try out", t: "Ela gosta de experimentar novas ideias." },
    { q: "They decided to ___ their differences. (settle)", k: "sort out", t: "Eles decidiram resolver suas diferenças." },
    { q: "I need to ___ the details. (verify)", k: "check out", t: "Preciso verificar os detalhes." },
    { q: "He will ___ his responsibilities. (avoid)", k: "get out of", t: "Ele vai se livrar de suas responsabilidades." },
    { q: "She likes to ___ on old friends. (visit informally)", k: "call on", t: "Ela gosta de visitar velhos amigos informalmente." },
    { q: "We need to ___ for the meeting. (prepare)", k: "get ready", t: "Precisamos nos preparar para a reunião." },
    { q: "He will ___ his promises. (fail to keep)", k: "break his promises|break his word", t: "Ele vai quebrar as promessas dele." },
    { q: "She will ___ the new system. (test)", k: "try out", t: "Ela vai testar o novo sistema." }
  ],
};
